// Code generated by protoc-gen-go. DO NOT EDIT.
// source: index.proto

package index

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IndexFieldType int32

const (
	IndexFieldType_TEXT      IndexFieldType = 0
	IndexFieldType_NUMERIC   IndexFieldType = 1
	IndexFieldType_BOOLEAN   IndexFieldType = 2
	IndexFieldType_GEO_POINT IndexFieldType = 3
	IndexFieldType_DATE_TIME IndexFieldType = 4
)

var IndexFieldType_name = map[int32]string{
	0: "TEXT",
	1: "NUMERIC",
	2: "BOOLEAN",
	3: "GEO_POINT",
	4: "DATE_TIME",
}

var IndexFieldType_value = map[string]int32{
	"TEXT":      0,
	"NUMERIC":   1,
	"BOOLEAN":   2,
	"GEO_POINT": 3,
	"DATE_TIME": 4,
}

func (x IndexFieldType) String() string {
	return proto.EnumName(IndexFieldType_name, int32(x))
}

func (IndexFieldType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{0}
}

type IndexField struct {
	IndexFieldType       IndexFieldType `protobuf:"varint,1,opt,name=indexFieldType,proto3,enum=index.IndexFieldType" json:"indexFieldType,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Analyzer             string         `protobuf:"bytes,3,opt,name=analyzer,proto3" json:"analyzer,omitempty"`
	Enabled              bool           `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Index                bool           `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	Store                bool           `protobuf:"varint,6,opt,name=store,proto3" json:"store,omitempty"`
	IncludeTermVectors   bool           `protobuf:"varint,7,opt,name=includeTermVectors,proto3" json:"includeTermVectors,omitempty"`
	IncludeInAll         bool           `protobuf:"varint,8,opt,name=includeInAll,proto3" json:"includeInAll,omitempty"`
	DocValues            bool           `protobuf:"varint,9,opt,name=docValues,proto3" json:"docValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *IndexField) Reset()         { *m = IndexField{} }
func (m *IndexField) String() string { return proto.CompactTextString(m) }
func (*IndexField) ProtoMessage()    {}
func (*IndexField) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{0}
}

func (m *IndexField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexField.Unmarshal(m, b)
}
func (m *IndexField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexField.Marshal(b, m, deterministic)
}
func (m *IndexField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexField.Merge(m, src)
}
func (m *IndexField) XXX_Size() int {
	return xxx_messageInfo_IndexField.Size(m)
}
func (m *IndexField) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexField.DiscardUnknown(m)
}

var xxx_messageInfo_IndexField proto.InternalMessageInfo

func (m *IndexField) GetIndexFieldType() IndexFieldType {
	if m != nil {
		return m.IndexFieldType
	}
	return IndexFieldType_TEXT
}

func (m *IndexField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IndexField) GetAnalyzer() string {
	if m != nil {
		return m.Analyzer
	}
	return ""
}

func (m *IndexField) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *IndexField) GetIndex() bool {
	if m != nil {
		return m.Index
	}
	return false
}

func (m *IndexField) GetStore() bool {
	if m != nil {
		return m.Store
	}
	return false
}

func (m *IndexField) GetIncludeTermVectors() bool {
	if m != nil {
		return m.IncludeTermVectors
	}
	return false
}

func (m *IndexField) GetIncludeInAll() bool {
	if m != nil {
		return m.IncludeInAll
	}
	return false
}

func (m *IndexField) GetDocValues() bool {
	if m != nil {
		return m.DocValues
	}
	return false
}

type IndexDocument struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Default              bool          `protobuf:"varint,2,opt,name=default,proto3" json:"default,omitempty"`
	IndexFieldList       []*IndexField `protobuf:"bytes,3,rep,name=indexFieldList,proto3" json:"indexFieldList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IndexDocument) Reset()         { *m = IndexDocument{} }
func (m *IndexDocument) String() string { return proto.CompactTextString(m) }
func (*IndexDocument) ProtoMessage()    {}
func (*IndexDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{1}
}

func (m *IndexDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexDocument.Unmarshal(m, b)
}
func (m *IndexDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexDocument.Marshal(b, m, deterministic)
}
func (m *IndexDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexDocument.Merge(m, src)
}
func (m *IndexDocument) XXX_Size() int {
	return xxx_messageInfo_IndexDocument.Size(m)
}
func (m *IndexDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexDocument.DiscardUnknown(m)
}

var xxx_messageInfo_IndexDocument proto.InternalMessageInfo

func (m *IndexDocument) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IndexDocument) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *IndexDocument) GetIndexFieldList() []*IndexField {
	if m != nil {
		return m.IndexFieldList
	}
	return nil
}

type IndexMeta struct {
	Namespace            []byte           `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version              uint32           `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Enabled              bool             `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Default              bool             `protobuf:"varint,4,opt,name=default,proto3" json:"default,omitempty"`
	CreatedAt            uint64           `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            uint64           `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	IndexDocumentList    []*IndexDocument `protobuf:"bytes,7,rep,name=indexDocumentList,proto3" json:"indexDocumentList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *IndexMeta) Reset()         { *m = IndexMeta{} }
func (m *IndexMeta) String() string { return proto.CompactTextString(m) }
func (*IndexMeta) ProtoMessage()    {}
func (*IndexMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{2}
}

func (m *IndexMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexMeta.Unmarshal(m, b)
}
func (m *IndexMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexMeta.Marshal(b, m, deterministic)
}
func (m *IndexMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexMeta.Merge(m, src)
}
func (m *IndexMeta) XXX_Size() int {
	return xxx_messageInfo_IndexMeta.Size(m)
}
func (m *IndexMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexMeta.DiscardUnknown(m)
}

var xxx_messageInfo_IndexMeta proto.InternalMessageInfo

func (m *IndexMeta) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *IndexMeta) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *IndexMeta) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *IndexMeta) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *IndexMeta) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *IndexMeta) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *IndexMeta) GetIndexDocumentList() []*IndexDocument {
	if m != nil {
		return m.IndexDocumentList
	}
	return nil
}

type IndexMetaList struct {
	IndexMetaList        []*IndexMeta `protobuf:"bytes,1,rep,name=indexMetaList,proto3" json:"indexMetaList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *IndexMetaList) Reset()         { *m = IndexMetaList{} }
func (m *IndexMetaList) String() string { return proto.CompactTextString(m) }
func (*IndexMetaList) ProtoMessage()    {}
func (*IndexMetaList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{3}
}

func (m *IndexMetaList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexMetaList.Unmarshal(m, b)
}
func (m *IndexMetaList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexMetaList.Marshal(b, m, deterministic)
}
func (m *IndexMetaList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexMetaList.Merge(m, src)
}
func (m *IndexMetaList) XXX_Size() int {
	return xxx_messageInfo_IndexMetaList.Size(m)
}
func (m *IndexMetaList) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexMetaList.DiscardUnknown(m)
}

var xxx_messageInfo_IndexMetaList proto.InternalMessageInfo

func (m *IndexMetaList) GetIndexMetaList() []*IndexMeta {
	if m != nil {
		return m.IndexMetaList
	}
	return nil
}

func init() {
	proto.RegisterEnum("index.IndexFieldType", IndexFieldType_name, IndexFieldType_value)
	proto.RegisterType((*IndexField)(nil), "index.IndexField")
	proto.RegisterType((*IndexDocument)(nil), "index.IndexDocument")
	proto.RegisterType((*IndexMeta)(nil), "index.IndexMeta")
	proto.RegisterType((*IndexMetaList)(nil), "index.IndexMetaList")
}

func init() { proto.RegisterFile("index.proto", fileDescriptor_f750e0f7889345b5) }

var fileDescriptor_f750e0f7889345b5 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x4f, 0x6b, 0xdb, 0x40,
	0x10, 0xc5, 0x2b, 0x4b, 0xb1, 0xa4, 0x71, 0x6c, 0x94, 0x21, 0x85, 0xa5, 0xe4, 0x60, 0x74, 0x32,
	0x3d, 0xf8, 0x90, 0x42, 0xa1, 0x87, 0x1e, 0x9c, 0x46, 0x0d, 0x82, 0xd8, 0x2e, 0x8b, 0x1a, 0x7a,
	0x0b, 0x8a, 0x34, 0x05, 0x81, 0x2c, 0x19, 0x69, 0x55, 0x92, 0x7e, 0xad, 0x7e, 0xb8, 0x5e, 0xcb,
	0x8e, 0xfc, 0x47, 0x8a, 0x7b, 0xdb, 0xf7, 0x7b, 0xcf, 0xbb, 0x33, 0xcf, 0x36, 0x8c, 0xb2, 0x22,
	0xa5, 0xe7, 0xf9, 0xb6, 0x2a, 0x55, 0x89, 0x67, 0x2c, 0xfc, 0x3f, 0x03, 0x80, 0x50, 0x9f, 0xbe,
	0x66, 0x94, 0xa7, 0xf8, 0x19, 0x26, 0xd9, 0x41, 0x45, 0x2f, 0x5b, 0x12, 0xc6, 0xd4, 0x98, 0x4d,
	0xae, 0xdf, 0xce, 0xdb, 0xcf, 0x86, 0x3d, 0x53, 0xbe, 0x0a, 0x23, 0x82, 0x55, 0xc4, 0x1b, 0x12,
	0x83, 0xa9, 0x31, 0x73, 0x25, 0x9f, 0xf1, 0x1d, 0x38, 0x71, 0x11, 0xe7, 0x2f, 0xbf, 0xa9, 0x12,
	0x26, 0xf3, 0x83, 0x46, 0x01, 0x36, 0x15, 0xf1, 0x53, 0x4e, 0xa9, 0xb0, 0xa6, 0xc6, 0xcc, 0x91,
	0x7b, 0x89, 0x97, 0xd0, 0x0e, 0x28, 0xce, 0x98, 0xb7, 0x42, 0xd3, 0x5a, 0x95, 0x15, 0x89, 0x61,
	0x4b, 0x59, 0xe0, 0x1c, 0x30, 0x2b, 0x92, 0xbc, 0x49, 0x29, 0xa2, 0x6a, 0xf3, 0x40, 0x89, 0x2a,
	0xab, 0x5a, 0xd8, 0x1c, 0xf9, 0x8f, 0x83, 0x3e, 0x9c, 0xef, 0x68, 0x58, 0x2c, 0xf2, 0x5c, 0x38,
	0x9c, 0xec, 0x31, 0xbc, 0x02, 0x37, 0x2d, 0x93, 0x87, 0x38, 0x6f, 0xa8, 0x16, 0x2e, 0x07, 0x8e,
	0xc0, 0x7f, 0x86, 0x31, 0x37, 0x71, 0x5b, 0x26, 0xcd, 0x86, 0x0a, 0x75, 0x58, 0xdc, 0xe8, 0x2c,
	0x2e, 0xc0, 0x4e, 0xe9, 0x67, 0xdc, 0xe4, 0x8a, 0xfb, 0x70, 0xe4, 0x5e, 0xe2, 0xa7, 0x6e, 0xcb,
	0xf7, 0x59, 0xad, 0x84, 0x39, 0x35, 0x67, 0xa3, 0xeb, 0x8b, 0x93, 0x96, 0xe5, 0xab, 0xa0, 0xff,
	0xd7, 0x00, 0x97, 0xed, 0x25, 0xa9, 0x58, 0x4f, 0xa9, 0x9f, 0xaa, 0xb7, 0x71, 0xd2, 0xbe, 0x7d,
	0x2e, 0x8f, 0x40, 0x0f, 0xf0, 0x8b, 0xaa, 0x3a, 0x2b, 0x0b, 0x1e, 0x60, 0x2c, 0xf7, 0xb2, 0xdb,
	0xbb, 0xd9, 0xef, 0xbd, 0x33, 0xb4, 0xd5, 0x1f, 0xfa, 0x0a, 0xdc, 0xa4, 0xa2, 0x58, 0x51, 0xba,
	0x50, 0xfc, 0xad, 0x58, 0xf2, 0x08, 0xb4, 0xdb, 0x6c, 0xd3, 0x9d, 0x3b, 0x6c, 0xdd, 0x03, 0xc0,
	0x1b, 0xb8, 0xc8, 0xba, 0x7d, 0xf1, 0xce, 0x36, 0xef, 0x7c, 0xd9, 0xdd, 0x79, 0xef, 0xcb, 0xd3,
	0xb8, 0x7f, 0xb7, 0xeb, 0x5c, 0x2f, 0xae, 0x01, 0x7e, 0x84, 0x71, 0xd6, 0x05, 0xc2, 0xe0, 0x0b,
	0xbd, 0xee, 0x85, 0xda, 0x93, 0xfd, 0xd8, 0x7b, 0x09, 0x93, 0xfe, 0xcf, 0x18, 0x1d, 0xb0, 0xa2,
	0xe0, 0x47, 0xe4, 0xbd, 0xc1, 0x11, 0xd8, 0xab, 0xef, 0xcb, 0x40, 0x86, 0x5f, 0x3c, 0x43, 0x8b,
	0x9b, 0xf5, 0xfa, 0x3e, 0x58, 0xac, 0xbc, 0x01, 0x8e, 0xc1, 0xbd, 0x0b, 0xd6, 0x8f, 0xdf, 0xd6,
	0xe1, 0x2a, 0xf2, 0x4c, 0x2d, 0x6f, 0x17, 0x51, 0xf0, 0x18, 0x85, 0xcb, 0xc0, 0xb3, 0x9e, 0x86,
	0xfc, 0xa7, 0xfa, 0xf0, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xad, 0xed, 0xd2, 0x7f, 0x63, 0x03, 0x00,
	0x00,
}
