// Code generated by protoc-gen-go. DO NOT EDIT.
// source: index.proto

package index

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	pb "github.com/mkawserm/flamed/pkg/pb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Action int32

const (
	Action_UPSERT Action = 0
	Action_DELETE Action = 1
)

var Action_name = map[int32]string{
	0: "UPSERT",
	1: "DELETE",
}

var Action_value = map[string]int32{
	"UPSERT": 0,
	"DELETE": 1,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{0}
}

type IndexPayload struct {
	Action               Action        `protobuf:"varint,1,opt,name=action,proto3,enum=index.Action" json:"action,omitempty"`
	IndexMeta            *pb.IndexMeta `protobuf:"bytes,2,opt,name=indexMeta,proto3" json:"indexMeta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IndexPayload) Reset()         { *m = IndexPayload{} }
func (m *IndexPayload) String() string { return proto.CompactTextString(m) }
func (*IndexPayload) ProtoMessage()    {}
func (*IndexPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{0}
}

func (m *IndexPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexPayload.Unmarshal(m, b)
}
func (m *IndexPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexPayload.Marshal(b, m, deterministic)
}
func (m *IndexPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexPayload.Merge(m, src)
}
func (m *IndexPayload) XXX_Size() int {
	return xxx_messageInfo_IndexPayload.Size(m)
}
func (m *IndexPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexPayload.DiscardUnknown(m)
}

var xxx_messageInfo_IndexPayload proto.InternalMessageInfo

func (m *IndexPayload) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_UPSERT
}

func (m *IndexPayload) GetIndexMeta() *pb.IndexMeta {
	if m != nil {
		return m.IndexMeta
	}
	return nil
}

func init() {
	proto.RegisterEnum("index.Action", Action_name, Action_value)
	proto.RegisterType((*IndexPayload)(nil), "index.IndexPayload")
}

func init() { proto.RegisterFile("index.proto", fileDescriptor_f750e0f7889345b5) }

var fileDescriptor_f750e0f7889345b5 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcc, 0x4b, 0x49,
	0xad, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0x84, 0x0b, 0xb2, 0xd3,
	0xf5, 0x0b, 0x92, 0xf4, 0xd3, 0x72, 0x12, 0x73, 0x53, 0x53, 0x20, 0x72, 0x4a, 0x49, 0x5c, 0x3c,
	0x9e, 0x20, 0xd9, 0x80, 0xc4, 0xca, 0x9c, 0xfc, 0xc4, 0x14, 0x21, 0x55, 0x2e, 0xb6, 0xc4, 0xe4,
	0x92, 0xcc, 0xfc, 0x3c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x5e, 0x3d, 0x88, 0x49, 0x8e,
	0x60, 0xc1, 0x20, 0xa8, 0xa4, 0x90, 0x36, 0x17, 0x27, 0x58, 0xdc, 0x37, 0xb5, 0x24, 0x51, 0x82,
	0x49, 0x81, 0x51, 0x83, 0xdb, 0x88, 0x57, 0xaf, 0x20, 0x49, 0xcf, 0x13, 0x26, 0x18, 0x84, 0x90,
	0xd7, 0x52, 0xe0, 0x62, 0x83, 0x68, 0x17, 0xe2, 0xe2, 0x62, 0x0b, 0x0d, 0x08, 0x76, 0x0d, 0x0a,
	0x11, 0x60, 0x00, 0xb1, 0x5d, 0x5c, 0x7d, 0x5c, 0x43, 0x5c, 0x05, 0x18, 0x93, 0xd8, 0xc0, 0x8e,
	0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xdd, 0x28, 0x5b, 0xb7, 0x00, 0x00, 0x00,
}
