// Code generated by protoc-gen-go. DO NOT EDIT.
// source: intkey.proto

package intkey

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Verb int32

const (
	Verb_INSERT    Verb = 0
	Verb_UPSERT    Verb = 1
	Verb_DELETE    Verb = 2
	Verb_INCREMENT Verb = 3
	Verb_DECREMENT Verb = 4
)

var Verb_name = map[int32]string{
	0: "INSERT",
	1: "UPSERT",
	2: "DELETE",
	3: "INCREMENT",
	4: "DECREMENT",
}

var Verb_value = map[string]int32{
	"INSERT":    0,
	"UPSERT":    1,
	"DELETE":    2,
	"INCREMENT": 3,
	"DECREMENT": 4,
}

func (x Verb) String() string {
	return proto.EnumName(Verb_name, int32(x))
}

func (Verb) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c97da48b2fb36873, []int{0}
}

type Payload struct {
	Verb                 Verb     `protobuf:"varint,1,opt,name=verb,proto3,enum=intkey.Verb" json:"verb,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                uint32   `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_c97da48b2fb36873, []int{0}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetVerb() Verb {
	if m != nil {
		return m.Verb
	}
	return Verb_INSERT
}

func (m *Payload) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Payload) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterEnum("intkey.Verb", Verb_name, Verb_value)
	proto.RegisterType((*Payload)(nil), "intkey.Payload")
}

func init() { proto.RegisterFile("intkey.proto", fileDescriptor_c97da48b2fb36873) }

var fileDescriptor_c97da48b2fb36873 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcc, 0x2b, 0xc9,
	0x4e, 0xad, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x42, 0xb9, 0xd8,
	0x03, 0x12, 0x2b, 0x73, 0xf2, 0x13, 0x53, 0x84, 0x14, 0xb8, 0x58, 0xca, 0x52, 0x8b, 0x92, 0x24,
	0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0x78, 0xf4, 0xa0, 0xea, 0xc3, 0x52, 0x8b, 0x92, 0x82, 0xc0,
	0x32, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41,
	0x60, 0xb6, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06,
	0x6f, 0x10, 0x84, 0xa3, 0xe5, 0xc1, 0xc5, 0x02, 0xd2, 0x27, 0xc4, 0xc5, 0xc5, 0xe6, 0xe9, 0x17,
	0xec, 0x1a, 0x14, 0x22, 0xc0, 0x00, 0x62, 0x87, 0x06, 0x80, 0xd9, 0x8c, 0x20, 0xb6, 0x8b, 0xab,
	0x8f, 0x6b, 0x88, 0xab, 0x00, 0x93, 0x10, 0x2f, 0x17, 0xa7, 0xa7, 0x9f, 0x73, 0x90, 0xab, 0xaf,
	0xab, 0x5f, 0x88, 0x00, 0x33, 0x88, 0xeb, 0xe2, 0x0a, 0xe3, 0xb2, 0x24, 0xb1, 0x81, 0xdd, 0x6b,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xb4, 0x89, 0xc2, 0xbf, 0x00, 0x00, 0x00,
}
