package constant

const LogLevel = "LogLevel"
const GlobalRequestTimeout = "GlobalRequestTimeout"
const StoragePath = "StoragePath"
const RaftAddress = "RaftAddress"
const Join = "Join"
const InitialMembers = "InitialMembers"

const HTTPServerTLS = "HTTPServerTLS"
const HTTPAddress = "HTTPAddress"
const HTTPServerCertFile = "HTTPServerCertFile"
const HTTPServerKeyFile = "HTTPServerKeyFile"

const DeploymentID = "DeploymentID"
const RTTMillisecond = "RTTMillisecond"
const MutualTLS = "MutualTLS"
const CAFile = "CAFile"
const CertFile = "CertFile"
const KeyFile = "KeyFile"
const MaxSendQueueSize = "MaxSendQueueSize"
const MaxReceiveQueueSize = "MaxReceiveQueueSize"
const EnableMetrics = "EnableMetrics"
const MaxSnapshotSendBytesPerSecond = "MaxSnapshotSendBytesPerSecond"
const MaxSnapshotRecvBytesPerSecond = "MaxSnapshotRecvBytesPerSecond"
const NotifyCommit = "NotifyCommit"
const LogDBConfig = "LogDBConfig"
const SystemTickerPrecision = "SystemTickerPrecision"

const NodeID = "NodeID"
const CheckQuorum = "CheckQuorum"
const ElectionRTT = "ElectionRTT"
const HeartbeatRTT = "HeartbeatRTT"
const SnapshotEntries = "SnapshotEntries"
const CompactionOverhead = "CompactionOverhead"
const OrderedConfigChange = "OrderedConfigChange"
const MaxInMemLogSize = "MaxInMemLogSize"
const DisableAutoCompactions = "DisableAutoCompactions"
const IsObserver = "IsObserver"
const IsWitness = "IsWitness"
const Quiesce = "Quiesce"
