// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flamed.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IndexFieldType int32

const (
	IndexFieldType_TEXT      IndexFieldType = 0
	IndexFieldType_NUMERIC   IndexFieldType = 1
	IndexFieldType_BOOLEAN   IndexFieldType = 2
	IndexFieldType_GEO_POINT IndexFieldType = 3
	IndexFieldType_DATE_TIME IndexFieldType = 4
)

var IndexFieldType_name = map[int32]string{
	0: "TEXT",
	1: "NUMERIC",
	2: "BOOLEAN",
	3: "GEO_POINT",
	4: "DATE_TIME",
}

var IndexFieldType_value = map[string]int32{
	"TEXT":      0,
	"NUMERIC":   1,
	"BOOLEAN":   2,
	"GEO_POINT": 3,
	"DATE_TIME": 4,
}

func (x IndexFieldType) String() string {
	return proto.EnumName(IndexFieldType_name, int32(x))
}

func (IndexFieldType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{0}
}

type Action int32

const (
	Action_GET     Action = 0
	Action_INSERT  Action = 1
	Action_UPDATE  Action = 2
	Action_UPSERT  Action = 3
	Action_DELETE  Action = 4
	Action_DEFAULT Action = 5
)

var Action_name = map[int32]string{
	0: "GET",
	1: "INSERT",
	2: "UPDATE",
	3: "UPSERT",
	4: "DELETE",
	5: "DEFAULT",
}

var Action_value = map[string]int32{
	"GET":     0,
	"INSERT":  1,
	"UPDATE":  2,
	"UPSERT":  3,
	"DELETE":  4,
	"DEFAULT": 5,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{1}
}

type UserType int32

const (
	UserType_SUPER_USER  UserType = 0
	UserType_NORMAL_USER UserType = 1
)

var UserType_name = map[int32]string{
	0: "SUPER_USER",
	1: "NORMAL_USER",
}

var UserType_value = map[string]int32{
	"SUPER_USER":  0,
	"NORMAL_USER": 1,
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}

func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{2}
}

type StateSnapshot struct {
	Uid                  []byte   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateSnapshot) Reset()         { *m = StateSnapshot{} }
func (m *StateSnapshot) String() string { return proto.CompactTextString(m) }
func (*StateSnapshot) ProtoMessage()    {}
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{0}
}

func (m *StateSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateSnapshot.Unmarshal(m, b)
}
func (m *StateSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateSnapshot.Marshal(b, m, deterministic)
}
func (m *StateSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateSnapshot.Merge(m, src)
}
func (m *StateSnapshot) XXX_Size() int {
	return xxx_messageInfo_StateSnapshot.Size(m)
}
func (m *StateSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_StateSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_StateSnapshot proto.InternalMessageInfo

func (m *StateSnapshot) GetUid() []byte {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *StateSnapshot) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type StateEntry struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Namespace            []byte   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	FamilyName           string   `protobuf:"bytes,3,opt,name=familyName,proto3" json:"familyName,omitempty"`
	FamilyVersion        string   `protobuf:"bytes,4,opt,name=familyVersion,proto3" json:"familyVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateEntry) Reset()         { *m = StateEntry{} }
func (m *StateEntry) String() string { return proto.CompactTextString(m) }
func (*StateEntry) ProtoMessage()    {}
func (*StateEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{1}
}

func (m *StateEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateEntry.Unmarshal(m, b)
}
func (m *StateEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateEntry.Marshal(b, m, deterministic)
}
func (m *StateEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateEntry.Merge(m, src)
}
func (m *StateEntry) XXX_Size() int {
	return xxx_messageInfo_StateEntry.Size(m)
}
func (m *StateEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_StateEntry.DiscardUnknown(m)
}

var xxx_messageInfo_StateEntry proto.InternalMessageInfo

func (m *StateEntry) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StateEntry) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *StateEntry) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *StateEntry) GetFamilyVersion() string {
	if m != nil {
		return m.FamilyVersion
	}
	return ""
}

type Transaction struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Namespace            []byte   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	FamilyName           string   `protobuf:"bytes,3,opt,name=familyName,proto3" json:"familyName,omitempty"`
	FamilyVersion        string   `protobuf:"bytes,4,opt,name=familyVersion,proto3" json:"familyVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{2}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Transaction) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *Transaction) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *Transaction) GetFamilyVersion() string {
	if m != nil {
		return m.FamilyVersion
	}
	return ""
}

type TransactionResponse struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode            uint32   `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorText            string   `protobuf:"bytes,3,opt,name=errorText,proto3" json:"errorText,omitempty"`
	FamilyName           string   `protobuf:"bytes,4,opt,name=familyName,proto3" json:"familyName,omitempty"`
	FamilyVersion        string   `protobuf:"bytes,5,opt,name=familyVersion,proto3" json:"familyVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionResponse) Reset()         { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()    {}
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{3}
}

func (m *TransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResponse.Unmarshal(m, b)
}
func (m *TransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResponse.Marshal(b, m, deterministic)
}
func (m *TransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResponse.Merge(m, src)
}
func (m *TransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionResponse.Size(m)
}
func (m *TransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResponse proto.InternalMessageInfo

func (m *TransactionResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TransactionResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *TransactionResponse) GetErrorText() string {
	if m != nil {
		return m.ErrorText
	}
	return ""
}

func (m *TransactionResponse) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *TransactionResponse) GetFamilyVersion() string {
	if m != nil {
		return m.FamilyVersion
	}
	return ""
}

type Proposal struct {
	Uuid                 []byte         `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Meta                 []byte         `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Remote               bool           `protobuf:"varint,3,opt,name=remote,proto3" json:"remote,omitempty"`
	CreatedAt            uint64         `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,5,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{4}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *Proposal) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Proposal) GetRemote() bool {
	if m != nil {
		return m.Remote
	}
	return false
}

func (m *Proposal) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Proposal) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type ProposalResponse struct {
	Uuid                 []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Status               uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode            uint32                 `protobuf:"varint,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorText            string                 `protobuf:"bytes,4,opt,name=errorText,proto3" json:"errorText,omitempty"`
	TransactionResponses []*TransactionResponse `protobuf:"bytes,5,rep,name=transactionResponses,proto3" json:"transactionResponses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ProposalResponse) Reset()         { *m = ProposalResponse{} }
func (m *ProposalResponse) String() string { return proto.CompactTextString(m) }
func (*ProposalResponse) ProtoMessage()    {}
func (*ProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{5}
}

func (m *ProposalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalResponse.Unmarshal(m, b)
}
func (m *ProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalResponse.Marshal(b, m, deterministic)
}
func (m *ProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalResponse.Merge(m, src)
}
func (m *ProposalResponse) XXX_Size() int {
	return xxx_messageInfo_ProposalResponse.Size(m)
}
func (m *ProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalResponse proto.InternalMessageInfo

func (m *ProposalResponse) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *ProposalResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ProposalResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *ProposalResponse) GetErrorText() string {
	if m != nil {
		return m.ErrorText
	}
	return ""
}

func (m *ProposalResponse) GetTransactionResponses() []*TransactionResponse {
	if m != nil {
		return m.TransactionResponses
	}
	return nil
}

type AppliedIndexQuery struct {
	AppliedIndex         uint64   `protobuf:"varint,1,opt,name=appliedIndex,proto3" json:"appliedIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppliedIndexQuery) Reset()         { *m = AppliedIndexQuery{} }
func (m *AppliedIndexQuery) String() string { return proto.CompactTextString(m) }
func (*AppliedIndexQuery) ProtoMessage()    {}
func (*AppliedIndexQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{6}
}

func (m *AppliedIndexQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppliedIndexQuery.Unmarshal(m, b)
}
func (m *AppliedIndexQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppliedIndexQuery.Marshal(b, m, deterministic)
}
func (m *AppliedIndexQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppliedIndexQuery.Merge(m, src)
}
func (m *AppliedIndexQuery) XXX_Size() int {
	return xxx_messageInfo_AppliedIndexQuery.Size(m)
}
func (m *AppliedIndexQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_AppliedIndexQuery.DiscardUnknown(m)
}

var xxx_messageInfo_AppliedIndexQuery proto.InternalMessageInfo

func (m *AppliedIndexQuery) GetAppliedIndex() uint64 {
	if m != nil {
		return m.AppliedIndex
	}
	return 0
}

type IndexField struct {
	IndexFieldType       IndexFieldType `protobuf:"varint,1,opt,name=indexFieldType,proto3,enum=pb.IndexFieldType" json:"indexFieldType,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Analyzer             string         `protobuf:"bytes,3,opt,name=analyzer,proto3" json:"analyzer,omitempty"`
	Enabled              bool           `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Index                bool           `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	Store                bool           `protobuf:"varint,6,opt,name=store,proto3" json:"store,omitempty"`
	IncludeTermVectors   bool           `protobuf:"varint,7,opt,name=includeTermVectors,proto3" json:"includeTermVectors,omitempty"`
	IncludeInAll         bool           `protobuf:"varint,8,opt,name=includeInAll,proto3" json:"includeInAll,omitempty"`
	DocValues            bool           `protobuf:"varint,9,opt,name=docValues,proto3" json:"docValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *IndexField) Reset()         { *m = IndexField{} }
func (m *IndexField) String() string { return proto.CompactTextString(m) }
func (*IndexField) ProtoMessage()    {}
func (*IndexField) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{7}
}

func (m *IndexField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexField.Unmarshal(m, b)
}
func (m *IndexField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexField.Marshal(b, m, deterministic)
}
func (m *IndexField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexField.Merge(m, src)
}
func (m *IndexField) XXX_Size() int {
	return xxx_messageInfo_IndexField.Size(m)
}
func (m *IndexField) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexField.DiscardUnknown(m)
}

var xxx_messageInfo_IndexField proto.InternalMessageInfo

func (m *IndexField) GetIndexFieldType() IndexFieldType {
	if m != nil {
		return m.IndexFieldType
	}
	return IndexFieldType_TEXT
}

func (m *IndexField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IndexField) GetAnalyzer() string {
	if m != nil {
		return m.Analyzer
	}
	return ""
}

func (m *IndexField) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *IndexField) GetIndex() bool {
	if m != nil {
		return m.Index
	}
	return false
}

func (m *IndexField) GetStore() bool {
	if m != nil {
		return m.Store
	}
	return false
}

func (m *IndexField) GetIncludeTermVectors() bool {
	if m != nil {
		return m.IncludeTermVectors
	}
	return false
}

func (m *IndexField) GetIncludeInAll() bool {
	if m != nil {
		return m.IncludeInAll
	}
	return false
}

func (m *IndexField) GetDocValues() bool {
	if m != nil {
		return m.DocValues
	}
	return false
}

type IndexDocument struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled              bool          `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Default              bool          `protobuf:"varint,3,opt,name=default,proto3" json:"default,omitempty"`
	IndexFieldList       []*IndexField `protobuf:"bytes,4,rep,name=indexFieldList,proto3" json:"indexFieldList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IndexDocument) Reset()         { *m = IndexDocument{} }
func (m *IndexDocument) String() string { return proto.CompactTextString(m) }
func (*IndexDocument) ProtoMessage()    {}
func (*IndexDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{8}
}

func (m *IndexDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexDocument.Unmarshal(m, b)
}
func (m *IndexDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexDocument.Marshal(b, m, deterministic)
}
func (m *IndexDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexDocument.Merge(m, src)
}
func (m *IndexDocument) XXX_Size() int {
	return xxx_messageInfo_IndexDocument.Size(m)
}
func (m *IndexDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexDocument.DiscardUnknown(m)
}

var xxx_messageInfo_IndexDocument proto.InternalMessageInfo

func (m *IndexDocument) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IndexDocument) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *IndexDocument) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *IndexDocument) GetIndexFieldList() []*IndexField {
	if m != nil {
		return m.IndexFieldList
	}
	return nil
}

type IndexMeta struct {
	Namespace            []byte           `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version              uint32           `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Enabled              bool             `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Default              bool             `protobuf:"varint,4,opt,name=default,proto3" json:"default,omitempty"`
	CreatedAt            uint64           `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            uint64           `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	IndexDocumentList    []*IndexDocument `protobuf:"bytes,7,rep,name=indexDocumentList,proto3" json:"indexDocumentList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *IndexMeta) Reset()         { *m = IndexMeta{} }
func (m *IndexMeta) String() string { return proto.CompactTextString(m) }
func (*IndexMeta) ProtoMessage()    {}
func (*IndexMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{9}
}

func (m *IndexMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexMeta.Unmarshal(m, b)
}
func (m *IndexMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexMeta.Marshal(b, m, deterministic)
}
func (m *IndexMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexMeta.Merge(m, src)
}
func (m *IndexMeta) XXX_Size() int {
	return xxx_messageInfo_IndexMeta.Size(m)
}
func (m *IndexMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexMeta.DiscardUnknown(m)
}

var xxx_messageInfo_IndexMeta proto.InternalMessageInfo

func (m *IndexMeta) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *IndexMeta) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *IndexMeta) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *IndexMeta) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *IndexMeta) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *IndexMeta) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *IndexMeta) GetIndexDocumentList() []*IndexDocument {
	if m != nil {
		return m.IndexDocumentList
	}
	return nil
}

type IndexMetaList struct {
	IndexMetaList        []*IndexMeta `protobuf:"bytes,1,rep,name=indexMetaList,proto3" json:"indexMetaList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *IndexMetaList) Reset()         { *m = IndexMetaList{} }
func (m *IndexMetaList) String() string { return proto.CompactTextString(m) }
func (*IndexMetaList) ProtoMessage()    {}
func (*IndexMetaList) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{10}
}

func (m *IndexMetaList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexMetaList.Unmarshal(m, b)
}
func (m *IndexMetaList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexMetaList.Marshal(b, m, deterministic)
}
func (m *IndexMetaList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexMetaList.Merge(m, src)
}
func (m *IndexMetaList) XXX_Size() int {
	return xxx_messageInfo_IndexMetaList.Size(m)
}
func (m *IndexMetaList) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexMetaList.DiscardUnknown(m)
}

var xxx_messageInfo_IndexMetaList proto.InternalMessageInfo

func (m *IndexMetaList) GetIndexMetaList() []*IndexMeta {
	if m != nil {
		return m.IndexMetaList
	}
	return nil
}

type IndexMetaPayload struct {
	Action               Action     `protobuf:"varint,1,opt,name=action,proto3,enum=pb.Action" json:"action,omitempty"`
	IndexMeta            *IndexMeta `protobuf:"bytes,2,opt,name=indexMeta,proto3" json:"indexMeta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IndexMetaPayload) Reset()         { *m = IndexMetaPayload{} }
func (m *IndexMetaPayload) String() string { return proto.CompactTextString(m) }
func (*IndexMetaPayload) ProtoMessage()    {}
func (*IndexMetaPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{11}
}

func (m *IndexMetaPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexMetaPayload.Unmarshal(m, b)
}
func (m *IndexMetaPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexMetaPayload.Marshal(b, m, deterministic)
}
func (m *IndexMetaPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexMetaPayload.Merge(m, src)
}
func (m *IndexMetaPayload) XXX_Size() int {
	return xxx_messageInfo_IndexMetaPayload.Size(m)
}
func (m *IndexMetaPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexMetaPayload.DiscardUnknown(m)
}

var xxx_messageInfo_IndexMetaPayload proto.InternalMessageInfo

func (m *IndexMetaPayload) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_GET
}

func (m *IndexMetaPayload) GetIndexMeta() *IndexMeta {
	if m != nil {
		return m.IndexMeta
	}
	return nil
}

type User struct {
	UserType             UserType `protobuf:"varint,1,opt,name=userType,proto3,enum=pb.UserType" json:"userType,omitempty"`
	Roles                string   `protobuf:"bytes,2,opt,name=roles,proto3" json:"roles,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt            uint64   `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            uint64   `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Data                 []byte   `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 []byte   `protobuf:"bytes,8,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{12}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserType() UserType {
	if m != nil {
		return m.UserType
	}
	return UserType_SUPER_USER
}

func (m *User) GetRoles() string {
	if m != nil {
		return m.Roles
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *User) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *User) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

type UserList struct {
	UserList             []*User  `protobuf:"bytes,1,rep,name=userList,proto3" json:"userList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{13}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetUserList() []*User {
	if m != nil {
		return m.UserList
	}
	return nil
}

type UsernameList struct {
	UsernameList         []string `protobuf:"bytes,1,rep,name=usernameList,proto3" json:"usernameList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsernameList) Reset()         { *m = UsernameList{} }
func (m *UsernameList) String() string { return proto.CompactTextString(m) }
func (*UsernameList) ProtoMessage()    {}
func (*UsernameList) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{14}
}

func (m *UsernameList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsernameList.Unmarshal(m, b)
}
func (m *UsernameList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsernameList.Marshal(b, m, deterministic)
}
func (m *UsernameList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsernameList.Merge(m, src)
}
func (m *UsernameList) XXX_Size() int {
	return xxx_messageInfo_UsernameList.Size(m)
}
func (m *UsernameList) XXX_DiscardUnknown() {
	xxx_messageInfo_UsernameList.DiscardUnknown(m)
}

var xxx_messageInfo_UsernameList proto.InternalMessageInfo

func (m *UsernameList) GetUsernameList() []string {
	if m != nil {
		return m.UsernameList
	}
	return nil
}

type UserPayload struct {
	Action               Action   `protobuf:"varint,1,opt,name=action,proto3,enum=pb.Action" json:"action,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPayload) Reset()         { *m = UserPayload{} }
func (m *UserPayload) String() string { return proto.CompactTextString(m) }
func (*UserPayload) ProtoMessage()    {}
func (*UserPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{15}
}

func (m *UserPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPayload.Unmarshal(m, b)
}
func (m *UserPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPayload.Marshal(b, m, deterministic)
}
func (m *UserPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPayload.Merge(m, src)
}
func (m *UserPayload) XXX_Size() int {
	return xxx_messageInfo_UserPayload.Size(m)
}
func (m *UserPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPayload.DiscardUnknown(m)
}

var xxx_messageInfo_UserPayload proto.InternalMessageInfo

func (m *UserPayload) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_GET
}

func (m *UserPayload) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type AccessControl struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Namespace            []byte   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Permission           []byte   `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	CreatedAt            uint64   `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            uint64   `protobuf:"varint,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Data                 []byte   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 []byte   `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessControl) Reset()         { *m = AccessControl{} }
func (m *AccessControl) String() string { return proto.CompactTextString(m) }
func (*AccessControl) ProtoMessage()    {}
func (*AccessControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{16}
}

func (m *AccessControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessControl.Unmarshal(m, b)
}
func (m *AccessControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessControl.Marshal(b, m, deterministic)
}
func (m *AccessControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessControl.Merge(m, src)
}
func (m *AccessControl) XXX_Size() int {
	return xxx_messageInfo_AccessControl.Size(m)
}
func (m *AccessControl) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessControl.DiscardUnknown(m)
}

var xxx_messageInfo_AccessControl proto.InternalMessageInfo

func (m *AccessControl) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccessControl) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *AccessControl) GetPermission() []byte {
	if m != nil {
		return m.Permission
	}
	return nil
}

func (m *AccessControl) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *AccessControl) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *AccessControl) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AccessControl) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

type AccessControlList struct {
	AccessControlList    []*AccessControl `protobuf:"bytes,1,rep,name=accessControlList,proto3" json:"accessControlList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AccessControlList) Reset()         { *m = AccessControlList{} }
func (m *AccessControlList) String() string { return proto.CompactTextString(m) }
func (*AccessControlList) ProtoMessage()    {}
func (*AccessControlList) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{17}
}

func (m *AccessControlList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessControlList.Unmarshal(m, b)
}
func (m *AccessControlList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessControlList.Marshal(b, m, deterministic)
}
func (m *AccessControlList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessControlList.Merge(m, src)
}
func (m *AccessControlList) XXX_Size() int {
	return xxx_messageInfo_AccessControlList.Size(m)
}
func (m *AccessControlList) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessControlList.DiscardUnknown(m)
}

var xxx_messageInfo_AccessControlList proto.InternalMessageInfo

func (m *AccessControlList) GetAccessControlList() []*AccessControl {
	if m != nil {
		return m.AccessControlList
	}
	return nil
}

type AccessControlPayload struct {
	Action               Action         `protobuf:"varint,1,opt,name=action,proto3,enum=pb.Action" json:"action,omitempty"`
	AccessControl        *AccessControl `protobuf:"bytes,2,opt,name=accessControl,proto3" json:"accessControl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AccessControlPayload) Reset()         { *m = AccessControlPayload{} }
func (m *AccessControlPayload) String() string { return proto.CompactTextString(m) }
func (*AccessControlPayload) ProtoMessage()    {}
func (*AccessControlPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{18}
}

func (m *AccessControlPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessControlPayload.Unmarshal(m, b)
}
func (m *AccessControlPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessControlPayload.Marshal(b, m, deterministic)
}
func (m *AccessControlPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessControlPayload.Merge(m, src)
}
func (m *AccessControlPayload) XXX_Size() int {
	return xxx_messageInfo_AccessControlPayload.Size(m)
}
func (m *AccessControlPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessControlPayload.DiscardUnknown(m)
}

var xxx_messageInfo_AccessControlPayload proto.InternalMessageInfo

func (m *AccessControlPayload) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_GET
}

func (m *AccessControlPayload) GetAccessControl() *AccessControl {
	if m != nil {
		return m.AccessControl
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.IndexFieldType", IndexFieldType_name, IndexFieldType_value)
	proto.RegisterEnum("pb.Action", Action_name, Action_value)
	proto.RegisterEnum("pb.UserType", UserType_name, UserType_value)
	proto.RegisterType((*StateSnapshot)(nil), "pb.StateSnapshot")
	proto.RegisterType((*StateEntry)(nil), "pb.StateEntry")
	proto.RegisterType((*Transaction)(nil), "pb.Transaction")
	proto.RegisterType((*TransactionResponse)(nil), "pb.TransactionResponse")
	proto.RegisterType((*Proposal)(nil), "pb.Proposal")
	proto.RegisterType((*ProposalResponse)(nil), "pb.ProposalResponse")
	proto.RegisterType((*AppliedIndexQuery)(nil), "pb.AppliedIndexQuery")
	proto.RegisterType((*IndexField)(nil), "pb.IndexField")
	proto.RegisterType((*IndexDocument)(nil), "pb.IndexDocument")
	proto.RegisterType((*IndexMeta)(nil), "pb.IndexMeta")
	proto.RegisterType((*IndexMetaList)(nil), "pb.IndexMetaList")
	proto.RegisterType((*IndexMetaPayload)(nil), "pb.IndexMetaPayload")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*UserList)(nil), "pb.UserList")
	proto.RegisterType((*UsernameList)(nil), "pb.UsernameList")
	proto.RegisterType((*UserPayload)(nil), "pb.UserPayload")
	proto.RegisterType((*AccessControl)(nil), "pb.AccessControl")
	proto.RegisterType((*AccessControlList)(nil), "pb.AccessControlList")
	proto.RegisterType((*AccessControlPayload)(nil), "pb.AccessControlPayload")
}

func init() { proto.RegisterFile("flamed.proto", fileDescriptor_388b6a0687b80922) }

var fileDescriptor_388b6a0687b80922 = []byte{
	// 1064 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x5d, 0x6e, 0xe3, 0x36,
	0x10, 0x5e, 0xd9, 0xb2, 0x2d, 0x4f, 0xec, 0xac, 0xcc, 0x06, 0xad, 0x50, 0x04, 0x45, 0x20, 0xec,
	0x43, 0x90, 0x05, 0x82, 0x22, 0x41, 0xbb, 0x40, 0x5f, 0x16, 0x6e, 0xa2, 0x5d, 0x18, 0x4d, 0xec,
	0x94, 0x91, 0x83, 0xbe, 0x05, 0x8c, 0xc5, 0xa0, 0x02, 0x64, 0x51, 0x20, 0xa9, 0x76, 0xdd, 0x23,
	0xb4, 0x0f, 0x3d, 0x41, 0xcf, 0xd0, 0xde, 0xa2, 0x4f, 0xbd, 0x44, 0xcf, 0xd0, 0x03, 0x14, 0xa4,
	0x68, 0xfd, 0x38, 0x4e, 0x83, 0x45, 0x1f, 0xf6, 0x8d, 0xf3, 0xcd, 0x90, 0xfa, 0xe6, 0x9b, 0x19,
	0x52, 0x30, 0xb8, 0x4f, 0xc8, 0x92, 0x46, 0xc7, 0x19, 0x67, 0x92, 0xa1, 0x56, 0x76, 0xe7, 0x7f,
	0x01, 0xc3, 0x6b, 0x49, 0x24, 0xbd, 0x4e, 0x49, 0x26, 0xbe, 0x67, 0x12, 0xb9, 0xd0, 0xce, 0xe3,
	0xc8, 0xb3, 0x0e, 0xac, 0xc3, 0x01, 0x56, 0x4b, 0x84, 0xc0, 0x8e, 0x88, 0x24, 0x5e, 0x4b, 0x43,
	0x7a, 0xed, 0xff, 0x6c, 0x01, 0xe8, 0x7d, 0x41, 0x2a, 0xf9, 0x0a, 0x79, 0xd0, 0xcb, 0xc8, 0x2a,
	0x61, 0x64, 0xbd, 0x71, 0x6d, 0xa2, 0x7d, 0xe8, 0xa7, 0x64, 0x49, 0x45, 0x46, 0x16, 0xd4, 0x9c,
	0x50, 0x01, 0xe8, 0x33, 0x80, 0x7b, 0xb2, 0x8c, 0x93, 0xd5, 0x94, 0x2c, 0xa9, 0xd7, 0x3e, 0xb0,
	0x0e, 0xfb, 0xb8, 0x86, 0xa0, 0x17, 0x30, 0x2c, 0xac, 0x1b, 0xca, 0x45, 0xcc, 0x52, 0xcf, 0xd6,
	0x21, 0x4d, 0xd0, 0xff, 0xc5, 0x82, 0x9d, 0x90, 0x93, 0x54, 0x90, 0x85, 0x8c, 0x59, 0xfa, 0x81,
	0xd9, 0xfc, 0x6e, 0xc1, 0x47, 0x35, 0x36, 0x98, 0x8a, 0x8c, 0xa5, 0x82, 0xa2, 0x8f, 0xa1, 0x2b,
	0x24, 0x91, 0xb9, 0xd0, 0xa4, 0x86, 0xd8, 0x58, 0x8a, 0x13, 0xe5, 0x9c, 0xf1, 0x33, 0x16, 0x15,
	0x9c, 0x86, 0xb8, 0x02, 0x4a, 0x6f, 0x48, 0xdf, 0x49, 0x43, 0xa9, 0x02, 0x36, 0x18, 0xdb, 0x4f,
	0x33, 0xee, 0x6c, 0x63, 0xfc, 0x9b, 0x05, 0xce, 0x15, 0x67, 0x19, 0x13, 0x24, 0x51, 0xd5, 0xce,
	0xab, 0x06, 0xd0, 0x6b, 0x85, 0x2d, 0x69, 0xd5, 0x01, 0x6a, 0xad, 0xd2, 0xe1, 0x74, 0xc9, 0x64,
	0x21, 0x94, 0x83, 0x8d, 0xa5, 0x08, 0x2f, 0x38, 0x25, 0x92, 0x46, 0x63, 0xa9, 0x19, 0xd9, 0xb8,
	0x02, 0xd0, 0x29, 0x0c, 0x64, 0xa5, 0x8d, 0xf0, 0x3a, 0x07, 0xed, 0xc3, 0x9d, 0x93, 0xe7, 0xc7,
	0xd9, 0xdd, 0x71, 0x5d, 0xb3, 0x46, 0x90, 0xff, 0xa7, 0x05, 0xee, 0x9a, 0x5f, 0x29, 0xe7, 0x36,
	0x9e, 0x95, 0xc4, 0xad, 0xc7, 0x25, 0x6e, 0xff, 0xa7, 0xc4, 0xf6, 0xa6, 0xc4, 0xdf, 0xc0, 0x9e,
	0x7c, 0x58, 0xcd, 0x35, 0xf3, 0x4f, 0x36, 0x99, 0x1b, 0x3f, 0xde, 0xba, 0xc9, 0x7f, 0x05, 0xa3,
	0x71, 0x96, 0x25, 0x31, 0x8d, 0x26, 0x69, 0x44, 0xdf, 0x7d, 0x9b, 0x53, 0xbe, 0x42, 0x3e, 0x0c,
	0x48, 0x0d, 0xd4, 0x19, 0xd9, 0xb8, 0x81, 0xf9, 0x7f, 0xb4, 0x00, 0xf4, 0xea, 0x4d, 0x4c, 0x93,
	0x08, 0x7d, 0x05, 0xbb, 0x71, 0x69, 0x85, 0xab, 0x8c, 0xea, 0x4d, 0xbb, 0x27, 0x48, 0xd1, 0x99,
	0x34, 0x3c, 0x78, 0x23, 0x52, 0x09, 0xa7, 0x5a, 0x5e, 0x4b, 0xd4, 0xc7, 0x7a, 0x8d, 0x3e, 0x05,
	0x87, 0xa4, 0x24, 0x59, 0xfd, 0x44, 0xb9, 0x69, 0xb2, 0xd2, 0x56, 0xd3, 0x44, 0x53, 0x72, 0x97,
	0xd0, 0x48, 0x8b, 0xe3, 0xe0, 0xb5, 0x89, 0xf6, 0xa0, 0xa3, 0xcf, 0xd6, 0x5d, 0xe5, 0xe0, 0xc2,
	0x50, 0xa8, 0x90, 0x8c, 0x53, 0xaf, 0x5b, 0xa0, 0xda, 0x40, 0xc7, 0x80, 0xe2, 0x74, 0x91, 0xe4,
	0x11, 0x0d, 0x29, 0x5f, 0xde, 0xd0, 0x85, 0x64, 0x5c, 0x78, 0x3d, 0x1d, 0xb2, 0xc5, 0xa3, 0x44,
	0x31, 0xe8, 0x24, 0x1d, 0x27, 0x89, 0xe7, 0xe8, 0xc8, 0x06, 0xa6, 0x0a, 0x17, 0xb1, 0xc5, 0x0d,
	0x49, 0x72, 0x2a, 0xbc, 0xbe, 0x0e, 0xa8, 0x00, 0xff, 0x57, 0x0b, 0x86, 0x5a, 0x8a, 0x73, 0xb6,
	0xc8, 0x97, 0x34, 0x95, 0x65, 0xe6, 0x56, 0x2d, 0xf3, 0x5a, 0x76, 0xad, 0x66, 0x76, 0x1e, 0xf4,
	0x22, 0x7a, 0x4f, 0xf2, 0x44, 0x9a, 0x0e, 0x5f, 0x9b, 0xe8, 0xcb, 0xba, 0xfa, 0x17, 0xb1, 0x50,
	0x5d, 0xa3, 0x9a, 0x61, 0xb7, 0xa9, 0x3e, 0xde, 0x88, 0xf2, 0xff, 0xb1, 0xa0, 0xaf, 0xdd, 0x97,
	0x6a, 0x80, 0x1a, 0x77, 0x91, 0xb5, 0x79, 0x17, 0x79, 0xd0, 0xfb, 0xc1, 0xcc, 0x6c, 0xd1, 0xcb,
	0x6b, 0xb3, 0xce, 0xb8, 0xfd, 0x28, 0x63, 0xbb, 0xc9, 0xb8, 0x31, 0x94, 0x9d, 0xcd, 0xa1, 0xdc,
	0x87, 0x7e, 0x9e, 0x45, 0xc6, 0xdb, 0x2d, 0xbc, 0x25, 0x80, 0x5e, 0xc3, 0x28, 0xae, 0xcb, 0xa8,
	0x13, 0xee, 0xe9, 0x84, 0x47, 0x65, 0xc2, 0x6b, 0x27, 0x7e, 0x18, 0xeb, 0x9f, 0x9b, 0x3a, 0xa8,
	0xac, 0x15, 0x80, 0x4e, 0x61, 0x18, 0xd7, 0x01, 0xcf, 0xd2, 0xa7, 0x0d, 0xcb, 0xd3, 0x94, 0x03,
	0x37, 0x63, 0xfc, 0x05, 0xb8, 0xa5, 0xef, 0xca, 0x5c, 0xe7, 0x3e, 0x74, 0x8b, 0x09, 0x33, 0xed,
	0x0f, 0xea, 0x84, 0x71, 0x31, 0x73, 0xc6, 0x83, 0x5e, 0x42, 0xbf, 0x3c, 0x48, 0x4b, 0xf9, 0xe0,
	0x43, 0x95, 0xdf, 0xff, 0xdb, 0x02, 0x7b, 0x2e, 0x28, 0x47, 0x87, 0xe0, 0xe4, 0x82, 0xf2, 0xda,
	0x68, 0x0d, 0xd4, 0xa6, 0xb9, 0xc1, 0x70, 0xe9, 0x55, 0xed, 0xce, 0x59, 0x42, 0x85, 0x99, 0xa7,
	0xc2, 0x50, 0x03, 0xa5, 0x22, 0xd2, 0xea, 0x21, 0x29, 0x6d, 0xe5, 0xcb, 0x88, 0x10, 0x3f, 0x32,
	0x1e, 0x99, 0xeb, 0xa6, 0xb4, 0xff, 0x57, 0xa1, 0xd6, 0xef, 0x74, 0xaf, 0x7a, 0xa7, 0xcb, 0x9b,
	0xdb, 0xa9, 0x6e, 0x6e, 0xff, 0x73, 0x70, 0x54, 0x1e, 0xba, 0x14, 0x2f, 0x0a, 0x9e, 0xb5, 0x2a,
	0x38, 0xeb, 0x3c, 0x71, 0xe9, 0xf1, 0x4f, 0x60, 0x30, 0x37, 0xec, 0xf5, 0x2e, 0x1f, 0x06, 0x79,
	0xcd, 0xd6, 0x3b, 0xfb, 0xb8, 0x81, 0xf9, 0x33, 0xd8, 0x51, 0x7b, 0xde, 0xa7, 0x54, 0xfb, 0x60,
	0xab, 0x23, 0x4c, 0x95, 0x2a, 0x22, 0x1a, 0xf5, 0xff, 0xb2, 0x60, 0x38, 0x5e, 0x2c, 0xa8, 0x10,
	0x67, 0x2c, 0x95, 0x9c, 0x25, 0x0d, 0x91, 0xad, 0x0d, 0x91, 0x9f, 0x7c, 0xe9, 0x33, 0xca, 0x97,
	0xb1, 0xd0, 0x03, 0xd6, 0xd6, 0xee, 0x1a, 0xf2, 0xc4, 0x23, 0xd6, 0x28, 0x43, 0xe7, 0xb1, 0x32,
	0x74, 0xb7, 0x94, 0xa1, 0x57, 0x2b, 0x43, 0x08, 0xa3, 0x46, 0x3a, 0x5a, 0xd9, 0xd7, 0x30, 0x22,
	0x9b, 0xa0, 0x29, 0xcc, 0xa8, 0x50, 0xac, 0xe6, 0xc4, 0x0f, 0x63, 0x7d, 0x01, 0x7b, 0x8d, 0x98,
	0xf7, 0xd1, 0xff, 0x15, 0x0c, 0x1b, 0x07, 0x9a, 0x42, 0x6c, 0xf9, 0x70, 0x33, 0xee, 0x08, 0xc3,
	0x6e, 0xf3, 0xd1, 0x41, 0x0e, 0xd8, 0x61, 0xf0, 0x5d, 0xe8, 0x3e, 0x43, 0x3b, 0xd0, 0x9b, 0xce,
	0x2f, 0x03, 0x3c, 0x39, 0x73, 0x2d, 0x65, 0x7c, 0x3d, 0x9b, 0x5d, 0x04, 0xe3, 0xa9, 0xdb, 0x42,
	0x43, 0xe8, 0xbf, 0x0d, 0x66, 0xb7, 0x57, 0xb3, 0xc9, 0x34, 0x74, 0xdb, 0xca, 0x3c, 0x1f, 0x87,
	0xc1, 0x6d, 0x38, 0xb9, 0x0c, 0x5c, 0xfb, 0x68, 0x0a, 0xdd, 0x82, 0x1e, 0xea, 0x41, 0xfb, 0x6d,
	0xa0, 0x8e, 0x02, 0xe8, 0x4e, 0xa6, 0xd7, 0x01, 0x0e, 0x5d, 0x4b, 0xad, 0xe7, 0x57, 0x2a, 0xde,
	0x6d, 0x15, 0x6b, 0x8d, 0xb7, 0xd5, 0xfa, 0x3c, 0xb8, 0x08, 0xc2, 0xc0, 0xb5, 0xd5, 0xd7, 0xce,
	0x83, 0x37, 0xe3, 0xf9, 0x45, 0xe8, 0x76, 0x8e, 0x5e, 0x16, 0x5d, 0xaf, 0xd9, 0xed, 0x02, 0x5c,
	0xcf, 0xaf, 0x02, 0x7c, 0x3b, 0xbf, 0x0e, 0xb0, 0xfb, 0x0c, 0x3d, 0x87, 0x9d, 0xe9, 0x0c, 0x5f,
	0x8e, 0x2f, 0x0a, 0xc0, 0xba, 0xeb, 0xea, 0x1f, 0xe4, 0xd3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x00, 0x9c, 0xd2, 0xe4, 0x30, 0x0b, 0x00, 0x00,
}
