// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flamed.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_REJECTED Status = 0
	Status_ACCEPTED Status = 1
)

var Status_name = map[int32]string{
	0: "REJECTED",
	1: "ACCEPTED",
}

var Status_value = map[string]int32{
	"REJECTED": 0,
	"ACCEPTED": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{0}
}

type IndexFieldType int32

const (
	IndexFieldType_TEXT      IndexFieldType = 0
	IndexFieldType_NUMERIC   IndexFieldType = 1
	IndexFieldType_BOOLEAN   IndexFieldType = 2
	IndexFieldType_GEO_POINT IndexFieldType = 3
	IndexFieldType_DATE_TIME IndexFieldType = 4
)

var IndexFieldType_name = map[int32]string{
	0: "TEXT",
	1: "NUMERIC",
	2: "BOOLEAN",
	3: "GEO_POINT",
	4: "DATE_TIME",
}

var IndexFieldType_value = map[string]int32{
	"TEXT":      0,
	"NUMERIC":   1,
	"BOOLEAN":   2,
	"GEO_POINT": 3,
	"DATE_TIME": 4,
}

func (x IndexFieldType) String() string {
	return proto.EnumName(IndexFieldType_name, int32(x))
}

func (IndexFieldType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{1}
}

type Action int32

const (
	Action_RETRIEVE Action = 0
	Action_SEARCH   Action = 1
	Action_ITERATE  Action = 2
	Action_MERGE    Action = 3
	Action_INSERT   Action = 4
	Action_UPDATE   Action = 5
	Action_UPSERT   Action = 6
	Action_DELETE   Action = 7
	Action_DEFAULT  Action = 8
)

var Action_name = map[int32]string{
	0: "RETRIEVE",
	1: "SEARCH",
	2: "ITERATE",
	3: "MERGE",
	4: "INSERT",
	5: "UPDATE",
	6: "UPSERT",
	7: "DELETE",
	8: "DEFAULT",
}

var Action_value = map[string]int32{
	"RETRIEVE": 0,
	"SEARCH":   1,
	"ITERATE":  2,
	"MERGE":    3,
	"INSERT":   4,
	"UPDATE":   5,
	"UPSERT":   6,
	"DELETE":   7,
	"DEFAULT":  8,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{2}
}

type UserType int32

const (
	UserType_SUPER_USER  UserType = 0
	UserType_NORMAL_USER UserType = 1
)

var UserType_name = map[int32]string{
	0: "SUPER_USER",
	1: "NORMAL_USER",
}

var UserType_value = map[string]int32{
	"SUPER_USER":  0,
	"NORMAL_USER": 1,
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}

func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{3}
}

type StateSnapshot struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateSnapshot) Reset()         { *m = StateSnapshot{} }
func (m *StateSnapshot) String() string { return proto.CompactTextString(m) }
func (*StateSnapshot) ProtoMessage()    {}
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{0}
}

func (m *StateSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateSnapshot.Unmarshal(m, b)
}
func (m *StateSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateSnapshot.Marshal(b, m, deterministic)
}
func (m *StateSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateSnapshot.Merge(m, src)
}
func (m *StateSnapshot) XXX_Size() int {
	return xxx_messageInfo_StateSnapshot.Size(m)
}
func (m *StateSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_StateSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_StateSnapshot proto.InternalMessageInfo

func (m *StateSnapshot) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *StateSnapshot) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type StateEntry struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Namespace            []byte   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	FamilyName           string   `protobuf:"bytes,3,opt,name=familyName,proto3" json:"familyName,omitempty"`
	FamilyVersion        string   `protobuf:"bytes,4,opt,name=familyVersion,proto3" json:"familyVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateEntry) Reset()         { *m = StateEntry{} }
func (m *StateEntry) String() string { return proto.CompactTextString(m) }
func (*StateEntry) ProtoMessage()    {}
func (*StateEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{1}
}

func (m *StateEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateEntry.Unmarshal(m, b)
}
func (m *StateEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateEntry.Marshal(b, m, deterministic)
}
func (m *StateEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateEntry.Merge(m, src)
}
func (m *StateEntry) XXX_Size() int {
	return xxx_messageInfo_StateEntry.Size(m)
}
func (m *StateEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_StateEntry.DiscardUnknown(m)
}

var xxx_messageInfo_StateEntry proto.InternalMessageInfo

func (m *StateEntry) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StateEntry) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *StateEntry) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *StateEntry) GetFamilyVersion() string {
	if m != nil {
		return m.FamilyVersion
	}
	return ""
}

type Transaction struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Namespace            []byte   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	FamilyName           string   `protobuf:"bytes,3,opt,name=familyName,proto3" json:"familyName,omitempty"`
	FamilyVersion        string   `protobuf:"bytes,4,opt,name=familyVersion,proto3" json:"familyVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{2}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Transaction) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *Transaction) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *Transaction) GetFamilyVersion() string {
	if m != nil {
		return m.FamilyVersion
	}
	return ""
}

type TransactionResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=pb.Status" json:"status,omitempty"`
	ErrorCode            uint32   `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorText            string   `protobuf:"bytes,3,opt,name=errorText,proto3" json:"errorText,omitempty"`
	FamilyName           string   `protobuf:"bytes,4,opt,name=familyName,proto3" json:"familyName,omitempty"`
	FamilyVersion        string   `protobuf:"bytes,5,opt,name=familyVersion,proto3" json:"familyVersion,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,6,opt,name=responseMessage,proto3" json:"responseMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionResponse) Reset()         { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()    {}
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{3}
}

func (m *TransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResponse.Unmarshal(m, b)
}
func (m *TransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResponse.Marshal(b, m, deterministic)
}
func (m *TransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResponse.Merge(m, src)
}
func (m *TransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionResponse.Size(m)
}
func (m *TransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResponse proto.InternalMessageInfo

func (m *TransactionResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_REJECTED
}

func (m *TransactionResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *TransactionResponse) GetErrorText() string {
	if m != nil {
		return m.ErrorText
	}
	return ""
}

func (m *TransactionResponse) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *TransactionResponse) GetFamilyVersion() string {
	if m != nil {
		return m.FamilyVersion
	}
	return ""
}

func (m *TransactionResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

type Proposal struct {
	Uuid                 []byte         `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Meta                 []byte         `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	CreatedAt            uint64         `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{4}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *Proposal) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Proposal) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Proposal) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type ProposalResponse struct {
	Uuid                 []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Status               Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=pb.Status" json:"status,omitempty"`
	ErrorCode            uint32                 `protobuf:"varint,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorText            string                 `protobuf:"bytes,4,opt,name=errorText,proto3" json:"errorText,omitempty"`
	TransactionResponses []*TransactionResponse `protobuf:"bytes,5,rep,name=transactionResponses,proto3" json:"transactionResponses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ProposalResponse) Reset()         { *m = ProposalResponse{} }
func (m *ProposalResponse) String() string { return proto.CompactTextString(m) }
func (*ProposalResponse) ProtoMessage()    {}
func (*ProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{5}
}

func (m *ProposalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalResponse.Unmarshal(m, b)
}
func (m *ProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalResponse.Marshal(b, m, deterministic)
}
func (m *ProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalResponse.Merge(m, src)
}
func (m *ProposalResponse) XXX_Size() int {
	return xxx_messageInfo_ProposalResponse.Size(m)
}
func (m *ProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalResponse proto.InternalMessageInfo

func (m *ProposalResponse) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *ProposalResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_REJECTED
}

func (m *ProposalResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *ProposalResponse) GetErrorText() string {
	if m != nil {
		return m.ErrorText
	}
	return ""
}

func (m *ProposalResponse) GetTransactionResponses() []*TransactionResponse {
	if m != nil {
		return m.TransactionResponses
	}
	return nil
}

type AppliedIndexQuery struct {
	AppliedIndex         uint64   `protobuf:"varint,1,opt,name=appliedIndex,proto3" json:"appliedIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppliedIndexQuery) Reset()         { *m = AppliedIndexQuery{} }
func (m *AppliedIndexQuery) String() string { return proto.CompactTextString(m) }
func (*AppliedIndexQuery) ProtoMessage()    {}
func (*AppliedIndexQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{6}
}

func (m *AppliedIndexQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppliedIndexQuery.Unmarshal(m, b)
}
func (m *AppliedIndexQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppliedIndexQuery.Marshal(b, m, deterministic)
}
func (m *AppliedIndexQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppliedIndexQuery.Merge(m, src)
}
func (m *AppliedIndexQuery) XXX_Size() int {
	return xxx_messageInfo_AppliedIndexQuery.Size(m)
}
func (m *AppliedIndexQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_AppliedIndexQuery.DiscardUnknown(m)
}

var xxx_messageInfo_AppliedIndexQuery proto.InternalMessageInfo

func (m *AppliedIndexQuery) GetAppliedIndex() uint64 {
	if m != nil {
		return m.AppliedIndex
	}
	return 0
}

type IndexField struct {
	IndexFieldType       IndexFieldType `protobuf:"varint,1,opt,name=indexFieldType,proto3,enum=pb.IndexFieldType" json:"indexFieldType,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Analyzer             string         `protobuf:"bytes,3,opt,name=analyzer,proto3" json:"analyzer,omitempty"`
	Enabled              bool           `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Index                bool           `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	Store                bool           `protobuf:"varint,6,opt,name=store,proto3" json:"store,omitempty"`
	IncludeTermVectors   bool           `protobuf:"varint,7,opt,name=includeTermVectors,proto3" json:"includeTermVectors,omitempty"`
	IncludeInAll         bool           `protobuf:"varint,8,opt,name=includeInAll,proto3" json:"includeInAll,omitempty"`
	DocValues            bool           `protobuf:"varint,9,opt,name=docValues,proto3" json:"docValues,omitempty"`
	DateFormat           string         `protobuf:"bytes,10,opt,name=dateFormat,proto3" json:"dateFormat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *IndexField) Reset()         { *m = IndexField{} }
func (m *IndexField) String() string { return proto.CompactTextString(m) }
func (*IndexField) ProtoMessage()    {}
func (*IndexField) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{7}
}

func (m *IndexField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexField.Unmarshal(m, b)
}
func (m *IndexField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexField.Marshal(b, m, deterministic)
}
func (m *IndexField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexField.Merge(m, src)
}
func (m *IndexField) XXX_Size() int {
	return xxx_messageInfo_IndexField.Size(m)
}
func (m *IndexField) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexField.DiscardUnknown(m)
}

var xxx_messageInfo_IndexField proto.InternalMessageInfo

func (m *IndexField) GetIndexFieldType() IndexFieldType {
	if m != nil {
		return m.IndexFieldType
	}
	return IndexFieldType_TEXT
}

func (m *IndexField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IndexField) GetAnalyzer() string {
	if m != nil {
		return m.Analyzer
	}
	return ""
}

func (m *IndexField) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *IndexField) GetIndex() bool {
	if m != nil {
		return m.Index
	}
	return false
}

func (m *IndexField) GetStore() bool {
	if m != nil {
		return m.Store
	}
	return false
}

func (m *IndexField) GetIncludeTermVectors() bool {
	if m != nil {
		return m.IncludeTermVectors
	}
	return false
}

func (m *IndexField) GetIncludeInAll() bool {
	if m != nil {
		return m.IncludeInAll
	}
	return false
}

func (m *IndexField) GetDocValues() bool {
	if m != nil {
		return m.DocValues
	}
	return false
}

func (m *IndexField) GetDateFormat() string {
	if m != nil {
		return m.DateFormat
	}
	return ""
}

type IndexDocument struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled              bool          `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Default              bool          `protobuf:"varint,3,opt,name=default,proto3" json:"default,omitempty"`
	Dynamic              bool          `protobuf:"varint,4,opt,name=dynamic,proto3" json:"dynamic,omitempty"`
	IndexFieldList       []*IndexField `protobuf:"bytes,5,rep,name=indexFieldList,proto3" json:"indexFieldList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IndexDocument) Reset()         { *m = IndexDocument{} }
func (m *IndexDocument) String() string { return proto.CompactTextString(m) }
func (*IndexDocument) ProtoMessage()    {}
func (*IndexDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{8}
}

func (m *IndexDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexDocument.Unmarshal(m, b)
}
func (m *IndexDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexDocument.Marshal(b, m, deterministic)
}
func (m *IndexDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexDocument.Merge(m, src)
}
func (m *IndexDocument) XXX_Size() int {
	return xxx_messageInfo_IndexDocument.Size(m)
}
func (m *IndexDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexDocument.DiscardUnknown(m)
}

var xxx_messageInfo_IndexDocument proto.InternalMessageInfo

func (m *IndexDocument) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IndexDocument) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *IndexDocument) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *IndexDocument) GetDynamic() bool {
	if m != nil {
		return m.Dynamic
	}
	return false
}

func (m *IndexDocument) GetIndexFieldList() []*IndexField {
	if m != nil {
		return m.IndexFieldList
	}
	return nil
}

type IndexMeta struct {
	Namespace             []byte           `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version               uint64           `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Enabled               bool             `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Default               bool             `protobuf:"varint,4,opt,name=default,proto3" json:"default,omitempty"`
	IndexDynamic          bool             `protobuf:"varint,5,opt,name=indexDynamic,proto3" json:"indexDynamic,omitempty"`
	StoreDynamic          bool             `protobuf:"varint,6,opt,name=storeDynamic,proto3" json:"storeDynamic,omitempty"`
	DocValuesDynamic      bool             `protobuf:"varint,7,opt,name=docValuesDynamic,proto3" json:"docValuesDynamic,omitempty"`
	DefaultType           string           `protobuf:"bytes,8,opt,name=defaultType,proto3" json:"defaultType,omitempty"`
	DefaultAnalyzer       string           `protobuf:"bytes,9,opt,name=defaultAnalyzer,proto3" json:"defaultAnalyzer,omitempty"`
	DefaultDateTimeParser string           `protobuf:"bytes,10,opt,name=defaultDateTimeParser,proto3" json:"defaultDateTimeParser,omitempty"`
	DefaultField          string           `protobuf:"bytes,11,opt,name=defaultField,proto3" json:"defaultField,omitempty"`
	TypeField             string           `protobuf:"bytes,12,opt,name=typeField,proto3" json:"typeField,omitempty"`
	CustomAnalysis        string           `protobuf:"bytes,13,opt,name=customAnalysis,proto3" json:"customAnalysis,omitempty"`
	CreatedAt             uint64           `protobuf:"varint,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt             uint64           `protobuf:"varint,15,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	IndexDocumentList     []*IndexDocument `protobuf:"bytes,16,rep,name=indexDocumentList,proto3" json:"indexDocumentList,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}         `json:"-"`
	XXX_unrecognized      []byte           `json:"-"`
	XXX_sizecache         int32            `json:"-"`
}

func (m *IndexMeta) Reset()         { *m = IndexMeta{} }
func (m *IndexMeta) String() string { return proto.CompactTextString(m) }
func (*IndexMeta) ProtoMessage()    {}
func (*IndexMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{9}
}

func (m *IndexMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexMeta.Unmarshal(m, b)
}
func (m *IndexMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexMeta.Marshal(b, m, deterministic)
}
func (m *IndexMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexMeta.Merge(m, src)
}
func (m *IndexMeta) XXX_Size() int {
	return xxx_messageInfo_IndexMeta.Size(m)
}
func (m *IndexMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexMeta.DiscardUnknown(m)
}

var xxx_messageInfo_IndexMeta proto.InternalMessageInfo

func (m *IndexMeta) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *IndexMeta) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *IndexMeta) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *IndexMeta) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *IndexMeta) GetIndexDynamic() bool {
	if m != nil {
		return m.IndexDynamic
	}
	return false
}

func (m *IndexMeta) GetStoreDynamic() bool {
	if m != nil {
		return m.StoreDynamic
	}
	return false
}

func (m *IndexMeta) GetDocValuesDynamic() bool {
	if m != nil {
		return m.DocValuesDynamic
	}
	return false
}

func (m *IndexMeta) GetDefaultType() string {
	if m != nil {
		return m.DefaultType
	}
	return ""
}

func (m *IndexMeta) GetDefaultAnalyzer() string {
	if m != nil {
		return m.DefaultAnalyzer
	}
	return ""
}

func (m *IndexMeta) GetDefaultDateTimeParser() string {
	if m != nil {
		return m.DefaultDateTimeParser
	}
	return ""
}

func (m *IndexMeta) GetDefaultField() string {
	if m != nil {
		return m.DefaultField
	}
	return ""
}

func (m *IndexMeta) GetTypeField() string {
	if m != nil {
		return m.TypeField
	}
	return ""
}

func (m *IndexMeta) GetCustomAnalysis() string {
	if m != nil {
		return m.CustomAnalysis
	}
	return ""
}

func (m *IndexMeta) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *IndexMeta) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *IndexMeta) GetIndexDocumentList() []*IndexDocument {
	if m != nil {
		return m.IndexDocumentList
	}
	return nil
}

type IndexMetaList struct {
	IndexMetaList        []*IndexMeta `protobuf:"bytes,1,rep,name=indexMetaList,proto3" json:"indexMetaList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *IndexMetaList) Reset()         { *m = IndexMetaList{} }
func (m *IndexMetaList) String() string { return proto.CompactTextString(m) }
func (*IndexMetaList) ProtoMessage()    {}
func (*IndexMetaList) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{10}
}

func (m *IndexMetaList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexMetaList.Unmarshal(m, b)
}
func (m *IndexMetaList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexMetaList.Marshal(b, m, deterministic)
}
func (m *IndexMetaList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexMetaList.Merge(m, src)
}
func (m *IndexMetaList) XXX_Size() int {
	return xxx_messageInfo_IndexMetaList.Size(m)
}
func (m *IndexMetaList) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexMetaList.DiscardUnknown(m)
}

var xxx_messageInfo_IndexMetaList proto.InternalMessageInfo

func (m *IndexMetaList) GetIndexMetaList() []*IndexMeta {
	if m != nil {
		return m.IndexMetaList
	}
	return nil
}

type IndexMetaPayload struct {
	Action               Action     `protobuf:"varint,1,opt,name=action,proto3,enum=pb.Action" json:"action,omitempty"`
	IndexMeta            *IndexMeta `protobuf:"bytes,2,opt,name=indexMeta,proto3" json:"indexMeta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IndexMetaPayload) Reset()         { *m = IndexMetaPayload{} }
func (m *IndexMetaPayload) String() string { return proto.CompactTextString(m) }
func (*IndexMetaPayload) ProtoMessage()    {}
func (*IndexMetaPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{11}
}

func (m *IndexMetaPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexMetaPayload.Unmarshal(m, b)
}
func (m *IndexMetaPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexMetaPayload.Marshal(b, m, deterministic)
}
func (m *IndexMetaPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexMetaPayload.Merge(m, src)
}
func (m *IndexMetaPayload) XXX_Size() int {
	return xxx_messageInfo_IndexMetaPayload.Size(m)
}
func (m *IndexMetaPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexMetaPayload.DiscardUnknown(m)
}

var xxx_messageInfo_IndexMetaPayload proto.InternalMessageInfo

func (m *IndexMetaPayload) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_RETRIEVE
}

func (m *IndexMetaPayload) GetIndexMeta() *IndexMeta {
	if m != nil {
		return m.IndexMeta
	}
	return nil
}

type User struct {
	UserType             UserType `protobuf:"varint,1,opt,name=userType,proto3,enum=pb.UserType" json:"userType,omitempty"`
	Roles                string   `protobuf:"bytes,2,opt,name=roles,proto3" json:"roles,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt            uint64   `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            uint64   `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Data                 []byte   `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 []byte   `protobuf:"bytes,8,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{12}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserType() UserType {
	if m != nil {
		return m.UserType
	}
	return UserType_SUPER_USER
}

func (m *User) GetRoles() string {
	if m != nil {
		return m.Roles
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *User) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *User) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

type UserList struct {
	UserList             []*User  `protobuf:"bytes,1,rep,name=userList,proto3" json:"userList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{13}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetUserList() []*User {
	if m != nil {
		return m.UserList
	}
	return nil
}

type UsernameList struct {
	UsernameList         []string `protobuf:"bytes,1,rep,name=usernameList,proto3" json:"usernameList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsernameList) Reset()         { *m = UsernameList{} }
func (m *UsernameList) String() string { return proto.CompactTextString(m) }
func (*UsernameList) ProtoMessage()    {}
func (*UsernameList) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{14}
}

func (m *UsernameList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsernameList.Unmarshal(m, b)
}
func (m *UsernameList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsernameList.Marshal(b, m, deterministic)
}
func (m *UsernameList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsernameList.Merge(m, src)
}
func (m *UsernameList) XXX_Size() int {
	return xxx_messageInfo_UsernameList.Size(m)
}
func (m *UsernameList) XXX_DiscardUnknown() {
	xxx_messageInfo_UsernameList.DiscardUnknown(m)
}

var xxx_messageInfo_UsernameList proto.InternalMessageInfo

func (m *UsernameList) GetUsernameList() []string {
	if m != nil {
		return m.UsernameList
	}
	return nil
}

type UserPayload struct {
	Action               Action   `protobuf:"varint,1,opt,name=action,proto3,enum=pb.Action" json:"action,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPayload) Reset()         { *m = UserPayload{} }
func (m *UserPayload) String() string { return proto.CompactTextString(m) }
func (*UserPayload) ProtoMessage()    {}
func (*UserPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{15}
}

func (m *UserPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPayload.Unmarshal(m, b)
}
func (m *UserPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPayload.Marshal(b, m, deterministic)
}
func (m *UserPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPayload.Merge(m, src)
}
func (m *UserPayload) XXX_Size() int {
	return xxx_messageInfo_UserPayload.Size(m)
}
func (m *UserPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPayload.DiscardUnknown(m)
}

var xxx_messageInfo_UserPayload proto.InternalMessageInfo

func (m *UserPayload) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_RETRIEVE
}

func (m *UserPayload) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type AccessControl struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Namespace            []byte   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Permission           uint64   `protobuf:"fixed64,3,opt,name=permission,proto3" json:"permission,omitempty"`
	CreatedAt            uint64   `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            uint64   `protobuf:"varint,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Data                 []byte   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 []byte   `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessControl) Reset()         { *m = AccessControl{} }
func (m *AccessControl) String() string { return proto.CompactTextString(m) }
func (*AccessControl) ProtoMessage()    {}
func (*AccessControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{16}
}

func (m *AccessControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessControl.Unmarshal(m, b)
}
func (m *AccessControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessControl.Marshal(b, m, deterministic)
}
func (m *AccessControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessControl.Merge(m, src)
}
func (m *AccessControl) XXX_Size() int {
	return xxx_messageInfo_AccessControl.Size(m)
}
func (m *AccessControl) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessControl.DiscardUnknown(m)
}

var xxx_messageInfo_AccessControl proto.InternalMessageInfo

func (m *AccessControl) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccessControl) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *AccessControl) GetPermission() uint64 {
	if m != nil {
		return m.Permission
	}
	return 0
}

func (m *AccessControl) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *AccessControl) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *AccessControl) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AccessControl) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

type AccessControlList struct {
	AccessControlList    []*AccessControl `protobuf:"bytes,1,rep,name=accessControlList,proto3" json:"accessControlList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AccessControlList) Reset()         { *m = AccessControlList{} }
func (m *AccessControlList) String() string { return proto.CompactTextString(m) }
func (*AccessControlList) ProtoMessage()    {}
func (*AccessControlList) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{17}
}

func (m *AccessControlList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessControlList.Unmarshal(m, b)
}
func (m *AccessControlList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessControlList.Marshal(b, m, deterministic)
}
func (m *AccessControlList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessControlList.Merge(m, src)
}
func (m *AccessControlList) XXX_Size() int {
	return xxx_messageInfo_AccessControlList.Size(m)
}
func (m *AccessControlList) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessControlList.DiscardUnknown(m)
}

var xxx_messageInfo_AccessControlList proto.InternalMessageInfo

func (m *AccessControlList) GetAccessControlList() []*AccessControl {
	if m != nil {
		return m.AccessControlList
	}
	return nil
}

type AccessControlPayload struct {
	Action               Action         `protobuf:"varint,1,opt,name=action,proto3,enum=pb.Action" json:"action,omitempty"`
	AccessControl        *AccessControl `protobuf:"bytes,2,opt,name=accessControl,proto3" json:"accessControl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AccessControlPayload) Reset()         { *m = AccessControlPayload{} }
func (m *AccessControlPayload) String() string { return proto.CompactTextString(m) }
func (*AccessControlPayload) ProtoMessage()    {}
func (*AccessControlPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{18}
}

func (m *AccessControlPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessControlPayload.Unmarshal(m, b)
}
func (m *AccessControlPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessControlPayload.Marshal(b, m, deterministic)
}
func (m *AccessControlPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessControlPayload.Merge(m, src)
}
func (m *AccessControlPayload) XXX_Size() int {
	return xxx_messageInfo_AccessControlPayload.Size(m)
}
func (m *AccessControlPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessControlPayload.DiscardUnknown(m)
}

var xxx_messageInfo_AccessControlPayload proto.InternalMessageInfo

func (m *AccessControlPayload) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_RETRIEVE
}

func (m *AccessControlPayload) GetAccessControl() *AccessControl {
	if m != nil {
		return m.AccessControl
	}
	return nil
}

type SearchInput struct {
	Namespace            []byte   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	FamilyName           string   `protobuf:"bytes,2,opt,name=familyName,proto3" json:"familyName,omitempty"`
	FamilyVersion        string   `protobuf:"bytes,3,opt,name=familyVersion,proto3" json:"familyVersion,omitempty"`
	Query                []byte   `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	From                 uint64   `protobuf:"varint,5,opt,name=from,proto3" json:"from,omitempty"`
	Limit                uint64   `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchInput) Reset()         { *m = SearchInput{} }
func (m *SearchInput) String() string { return proto.CompactTextString(m) }
func (*SearchInput) ProtoMessage()    {}
func (*SearchInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{19}
}

func (m *SearchInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchInput.Unmarshal(m, b)
}
func (m *SearchInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchInput.Marshal(b, m, deterministic)
}
func (m *SearchInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchInput.Merge(m, src)
}
func (m *SearchInput) XXX_Size() int {
	return xxx_messageInfo_SearchInput.Size(m)
}
func (m *SearchInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchInput.DiscardUnknown(m)
}

var xxx_messageInfo_SearchInput proto.InternalMessageInfo

func (m *SearchInput) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *SearchInput) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *SearchInput) GetFamilyVersion() string {
	if m != nil {
		return m.FamilyVersion
	}
	return ""
}

func (m *SearchInput) GetQuery() []byte {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *SearchInput) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SearchInput) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type IterateInput struct {
	Namespace            []byte   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	FamilyName           string   `protobuf:"bytes,2,opt,name=familyName,proto3" json:"familyName,omitempty"`
	FamilyVersion        string   `protobuf:"bytes,3,opt,name=familyVersion,proto3" json:"familyVersion,omitempty"`
	From                 []byte   `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	Prefix               []byte   `protobuf:"bytes,5,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Limit                uint64   `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IterateInput) Reset()         { *m = IterateInput{} }
func (m *IterateInput) String() string { return proto.CompactTextString(m) }
func (*IterateInput) ProtoMessage()    {}
func (*IterateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{20}
}

func (m *IterateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IterateInput.Unmarshal(m, b)
}
func (m *IterateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IterateInput.Marshal(b, m, deterministic)
}
func (m *IterateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IterateInput.Merge(m, src)
}
func (m *IterateInput) XXX_Size() int {
	return xxx_messageInfo_IterateInput.Size(m)
}
func (m *IterateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_IterateInput.DiscardUnknown(m)
}

var xxx_messageInfo_IterateInput proto.InternalMessageInfo

func (m *IterateInput) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *IterateInput) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *IterateInput) GetFamilyVersion() string {
	if m != nil {
		return m.FamilyVersion
	}
	return ""
}

func (m *IterateInput) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *IterateInput) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *IterateInput) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type RetrieveInput struct {
	Namespace            []byte   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	FamilyName           string   `protobuf:"bytes,2,opt,name=familyName,proto3" json:"familyName,omitempty"`
	FamilyVersion        string   `protobuf:"bytes,3,opt,name=familyVersion,proto3" json:"familyVersion,omitempty"`
	Addresses            [][]byte `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveInput) Reset()         { *m = RetrieveInput{} }
func (m *RetrieveInput) String() string { return proto.CompactTextString(m) }
func (*RetrieveInput) ProtoMessage()    {}
func (*RetrieveInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{21}
}

func (m *RetrieveInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveInput.Unmarshal(m, b)
}
func (m *RetrieveInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveInput.Marshal(b, m, deterministic)
}
func (m *RetrieveInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveInput.Merge(m, src)
}
func (m *RetrieveInput) XXX_Size() int {
	return xxx_messageInfo_RetrieveInput.Size(m)
}
func (m *RetrieveInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveInput.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveInput proto.InternalMessageInfo

func (m *RetrieveInput) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *RetrieveInput) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *RetrieveInput) GetFamilyVersion() string {
	if m != nil {
		return m.FamilyVersion
	}
	return ""
}

func (m *RetrieveInput) GetAddresses() [][]byte {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type GlobalIterateInput struct {
	Namespace            []byte   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	From                 []byte   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Prefix               []byte   `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Limit                uint64   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalIterateInput) Reset()         { *m = GlobalIterateInput{} }
func (m *GlobalIterateInput) String() string { return proto.CompactTextString(m) }
func (*GlobalIterateInput) ProtoMessage()    {}
func (*GlobalIterateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{22}
}

func (m *GlobalIterateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalIterateInput.Unmarshal(m, b)
}
func (m *GlobalIterateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalIterateInput.Marshal(b, m, deterministic)
}
func (m *GlobalIterateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalIterateInput.Merge(m, src)
}
func (m *GlobalIterateInput) XXX_Size() int {
	return xxx_messageInfo_GlobalIterateInput.Size(m)
}
func (m *GlobalIterateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalIterateInput.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalIterateInput proto.InternalMessageInfo

func (m *GlobalIterateInput) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *GlobalIterateInput) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *GlobalIterateInput) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *GlobalIterateInput) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GlobalRetrieveInput struct {
	Namespace            []byte   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Addresses            [][]byte `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalRetrieveInput) Reset()         { *m = GlobalRetrieveInput{} }
func (m *GlobalRetrieveInput) String() string { return proto.CompactTextString(m) }
func (*GlobalRetrieveInput) ProtoMessage()    {}
func (*GlobalRetrieveInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{23}
}

func (m *GlobalRetrieveInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalRetrieveInput.Unmarshal(m, b)
}
func (m *GlobalRetrieveInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalRetrieveInput.Marshal(b, m, deterministic)
}
func (m *GlobalRetrieveInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalRetrieveInput.Merge(m, src)
}
func (m *GlobalRetrieveInput) XXX_Size() int {
	return xxx_messageInfo_GlobalRetrieveInput.Size(m)
}
func (m *GlobalRetrieveInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalRetrieveInput.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalRetrieveInput proto.InternalMessageInfo

func (m *GlobalRetrieveInput) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *GlobalRetrieveInput) GetAddresses() [][]byte {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type GlobalDeleteInput struct {
	Namespace            []byte   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Addresses            [][]byte `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalDeleteInput) Reset()         { *m = GlobalDeleteInput{} }
func (m *GlobalDeleteInput) String() string { return proto.CompactTextString(m) }
func (*GlobalDeleteInput) ProtoMessage()    {}
func (*GlobalDeleteInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{24}
}

func (m *GlobalDeleteInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalDeleteInput.Unmarshal(m, b)
}
func (m *GlobalDeleteInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalDeleteInput.Marshal(b, m, deterministic)
}
func (m *GlobalDeleteInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalDeleteInput.Merge(m, src)
}
func (m *GlobalDeleteInput) XXX_Size() int {
	return xxx_messageInfo_GlobalDeleteInput.Size(m)
}
func (m *GlobalDeleteInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalDeleteInput.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalDeleteInput proto.InternalMessageInfo

func (m *GlobalDeleteInput) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *GlobalDeleteInput) GetAddresses() [][]byte {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type StateEntryResponse struct {
	StateAvailable       bool        `protobuf:"varint,1,opt,name=stateAvailable,proto3" json:"stateAvailable,omitempty"`
	Address              string      `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	StateEntry           *StateEntry `protobuf:"bytes,3,opt,name=stateEntry,proto3" json:"stateEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StateEntryResponse) Reset()         { *m = StateEntryResponse{} }
func (m *StateEntryResponse) String() string { return proto.CompactTextString(m) }
func (*StateEntryResponse) ProtoMessage()    {}
func (*StateEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{25}
}

func (m *StateEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateEntryResponse.Unmarshal(m, b)
}
func (m *StateEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateEntryResponse.Marshal(b, m, deterministic)
}
func (m *StateEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateEntryResponse.Merge(m, src)
}
func (m *StateEntryResponse) XXX_Size() int {
	return xxx_messageInfo_StateEntryResponse.Size(m)
}
func (m *StateEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StateEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StateEntryResponse proto.InternalMessageInfo

func (m *StateEntryResponse) GetStateAvailable() bool {
	if m != nil {
		return m.StateAvailable
	}
	return false
}

func (m *StateEntryResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *StateEntryResponse) GetStateEntry() *StateEntry {
	if m != nil {
		return m.StateEntry
	}
	return nil
}

type DateTimeRangeFacet struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Start                string   `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DateTimeRangeFacet) Reset()         { *m = DateTimeRangeFacet{} }
func (m *DateTimeRangeFacet) String() string { return proto.CompactTextString(m) }
func (*DateTimeRangeFacet) ProtoMessage()    {}
func (*DateTimeRangeFacet) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{26}
}

func (m *DateTimeRangeFacet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateTimeRangeFacet.Unmarshal(m, b)
}
func (m *DateTimeRangeFacet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateTimeRangeFacet.Marshal(b, m, deterministic)
}
func (m *DateTimeRangeFacet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateTimeRangeFacet.Merge(m, src)
}
func (m *DateTimeRangeFacet) XXX_Size() int {
	return xxx_messageInfo_DateTimeRangeFacet.Size(m)
}
func (m *DateTimeRangeFacet) XXX_DiscardUnknown() {
	xxx_messageInfo_DateTimeRangeFacet.DiscardUnknown(m)
}

var xxx_messageInfo_DateTimeRangeFacet proto.InternalMessageInfo

func (m *DateTimeRangeFacet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DateTimeRangeFacet) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *DateTimeRangeFacet) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type NumericRangeFacet struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Min                  float64  `protobuf:"fixed64,2,opt,name=min,proto3" json:"min,omitempty"`
	Max                  float64  `protobuf:"fixed64,3,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumericRangeFacet) Reset()         { *m = NumericRangeFacet{} }
func (m *NumericRangeFacet) String() string { return proto.CompactTextString(m) }
func (*NumericRangeFacet) ProtoMessage()    {}
func (*NumericRangeFacet) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{27}
}

func (m *NumericRangeFacet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumericRangeFacet.Unmarshal(m, b)
}
func (m *NumericRangeFacet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumericRangeFacet.Marshal(b, m, deterministic)
}
func (m *NumericRangeFacet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumericRangeFacet.Merge(m, src)
}
func (m *NumericRangeFacet) XXX_Size() int {
	return xxx_messageInfo_NumericRangeFacet.Size(m)
}
func (m *NumericRangeFacet) XXX_DiscardUnknown() {
	xxx_messageInfo_NumericRangeFacet.DiscardUnknown(m)
}

var xxx_messageInfo_NumericRangeFacet proto.InternalMessageInfo

func (m *NumericRangeFacet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NumericRangeFacet) GetMin() float64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *NumericRangeFacet) GetMax() float64 {
	if m != nil {
		return m.Max
	}
	return 0
}

type Facet struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Field                string                `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Size                 int32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	DateTimeRangeFacets  []*DateTimeRangeFacet `protobuf:"bytes,4,rep,name=dateTimeRangeFacets,proto3" json:"dateTimeRangeFacets,omitempty"`
	NumericRangeFacets   []*NumericRangeFacet  `protobuf:"bytes,5,rep,name=numericRangeFacets,proto3" json:"numericRangeFacets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Facet) Reset()         { *m = Facet{} }
func (m *Facet) String() string { return proto.CompactTextString(m) }
func (*Facet) ProtoMessage()    {}
func (*Facet) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{28}
}

func (m *Facet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Facet.Unmarshal(m, b)
}
func (m *Facet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Facet.Marshal(b, m, deterministic)
}
func (m *Facet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Facet.Merge(m, src)
}
func (m *Facet) XXX_Size() int {
	return xxx_messageInfo_Facet.Size(m)
}
func (m *Facet) XXX_DiscardUnknown() {
	xxx_messageInfo_Facet.DiscardUnknown(m)
}

var xxx_messageInfo_Facet proto.InternalMessageInfo

func (m *Facet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Facet) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Facet) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Facet) GetDateTimeRangeFacets() []*DateTimeRangeFacet {
	if m != nil {
		return m.DateTimeRangeFacets
	}
	return nil
}

func (m *Facet) GetNumericRangeFacets() []*NumericRangeFacet {
	if m != nil {
		return m.NumericRangeFacets
	}
	return nil
}

type QueryString struct {
	Q                    string   `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryString) Reset()         { *m = QueryString{} }
func (m *QueryString) String() string { return proto.CompactTextString(m) }
func (*QueryString) ProtoMessage()    {}
func (*QueryString) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{29}
}

func (m *QueryString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryString.Unmarshal(m, b)
}
func (m *QueryString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryString.Marshal(b, m, deterministic)
}
func (m *QueryString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryString.Merge(m, src)
}
func (m *QueryString) XXX_Size() int {
	return xxx_messageInfo_QueryString.Size(m)
}
func (m *QueryString) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryString.DiscardUnknown(m)
}

var xxx_messageInfo_QueryString proto.InternalMessageInfo

func (m *QueryString) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

type Fuzzy struct {
	Term                 string   `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Fuzziness            int32    `protobuf:"varint,2,opt,name=fuzziness,proto3" json:"fuzziness,omitempty"`
	Field                string   `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	PrefixLength         string   `protobuf:"bytes,4,opt,name=prefixLength,proto3" json:"prefixLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fuzzy) Reset()         { *m = Fuzzy{} }
func (m *Fuzzy) String() string { return proto.CompactTextString(m) }
func (*Fuzzy) ProtoMessage()    {}
func (*Fuzzy) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{30}
}

func (m *Fuzzy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fuzzy.Unmarshal(m, b)
}
func (m *Fuzzy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fuzzy.Marshal(b, m, deterministic)
}
func (m *Fuzzy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fuzzy.Merge(m, src)
}
func (m *Fuzzy) XXX_Size() int {
	return xxx_messageInfo_Fuzzy.Size(m)
}
func (m *Fuzzy) XXX_DiscardUnknown() {
	xxx_messageInfo_Fuzzy.DiscardUnknown(m)
}

var xxx_messageInfo_Fuzzy proto.InternalMessageInfo

func (m *Fuzzy) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

func (m *Fuzzy) GetFuzziness() int32 {
	if m != nil {
		return m.Fuzziness
	}
	return 0
}

func (m *Fuzzy) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Fuzzy) GetPrefixLength() string {
	if m != nil {
		return m.PrefixLength
	}
	return ""
}

type Regexp struct {
	Regexp               string   `protobuf:"bytes,1,opt,name=regexp,proto3" json:"regexp,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Regexp) Reset()         { *m = Regexp{} }
func (m *Regexp) String() string { return proto.CompactTextString(m) }
func (*Regexp) ProtoMessage()    {}
func (*Regexp) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{31}
}

func (m *Regexp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Regexp.Unmarshal(m, b)
}
func (m *Regexp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Regexp.Marshal(b, m, deterministic)
}
func (m *Regexp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Regexp.Merge(m, src)
}
func (m *Regexp) XXX_Size() int {
	return xxx_messageInfo_Regexp.Size(m)
}
func (m *Regexp) XXX_DiscardUnknown() {
	xxx_messageInfo_Regexp.DiscardUnknown(m)
}

var xxx_messageInfo_Regexp proto.InternalMessageInfo

func (m *Regexp) GetRegexp() string {
	if m != nil {
		return m.Regexp
	}
	return ""
}

func (m *Regexp) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type Term struct {
	Term                 string   `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Term) Reset()         { *m = Term{} }
func (m *Term) String() string { return proto.CompactTextString(m) }
func (*Term) ProtoMessage()    {}
func (*Term) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{32}
}

func (m *Term) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Term.Unmarshal(m, b)
}
func (m *Term) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Term.Marshal(b, m, deterministic)
}
func (m *Term) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Term.Merge(m, src)
}
func (m *Term) XXX_Size() int {
	return xxx_messageInfo_Term.Size(m)
}
func (m *Term) XXX_DiscardUnknown() {
	xxx_messageInfo_Term.DiscardUnknown(m)
}

var xxx_messageInfo_Term proto.InternalMessageInfo

func (m *Term) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

func (m *Term) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type MatchPhrase struct {
	MatchPhrase          string   `protobuf:"bytes,1,opt,name=matchPhrase,proto3" json:"matchPhrase,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchPhrase) Reset()         { *m = MatchPhrase{} }
func (m *MatchPhrase) String() string { return proto.CompactTextString(m) }
func (*MatchPhrase) ProtoMessage()    {}
func (*MatchPhrase) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{33}
}

func (m *MatchPhrase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchPhrase.Unmarshal(m, b)
}
func (m *MatchPhrase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchPhrase.Marshal(b, m, deterministic)
}
func (m *MatchPhrase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchPhrase.Merge(m, src)
}
func (m *MatchPhrase) XXX_Size() int {
	return xxx_messageInfo_MatchPhrase.Size(m)
}
func (m *MatchPhrase) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchPhrase.DiscardUnknown(m)
}

var xxx_messageInfo_MatchPhrase proto.InternalMessageInfo

func (m *MatchPhrase) GetMatchPhrase() string {
	if m != nil {
		return m.MatchPhrase
	}
	return ""
}

func (m *MatchPhrase) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type Match struct {
	Match                string   `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Match) Reset()         { *m = Match{} }
func (m *Match) String() string { return proto.CompactTextString(m) }
func (*Match) ProtoMessage()    {}
func (*Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{34}
}

func (m *Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Match.Unmarshal(m, b)
}
func (m *Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Match.Marshal(b, m, deterministic)
}
func (m *Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Match.Merge(m, src)
}
func (m *Match) XXX_Size() int {
	return xxx_messageInfo_Match.Size(m)
}
func (m *Match) XXX_DiscardUnknown() {
	xxx_messageInfo_Match.DiscardUnknown(m)
}

var xxx_messageInfo_Match proto.InternalMessageInfo

func (m *Match) GetMatch() string {
	if m != nil {
		return m.Match
	}
	return ""
}

func (m *Match) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type Prefix struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prefix) Reset()         { *m = Prefix{} }
func (m *Prefix) String() string { return proto.CompactTextString(m) }
func (*Prefix) ProtoMessage()    {}
func (*Prefix) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{35}
}

func (m *Prefix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prefix.Unmarshal(m, b)
}
func (m *Prefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prefix.Marshal(b, m, deterministic)
}
func (m *Prefix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prefix.Merge(m, src)
}
func (m *Prefix) XXX_Size() int {
	return xxx_messageInfo_Prefix.Size(m)
}
func (m *Prefix) XXX_DiscardUnknown() {
	xxx_messageInfo_Prefix.DiscardUnknown(m)
}

var xxx_messageInfo_Prefix proto.InternalMessageInfo

func (m *Prefix) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Prefix) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type Wildcard struct {
	Wildcard             string   `protobuf:"bytes,1,opt,name=wildcard,proto3" json:"wildcard,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wildcard) Reset()         { *m = Wildcard{} }
func (m *Wildcard) String() string { return proto.CompactTextString(m) }
func (*Wildcard) ProtoMessage()    {}
func (*Wildcard) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{36}
}

func (m *Wildcard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wildcard.Unmarshal(m, b)
}
func (m *Wildcard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wildcard.Marshal(b, m, deterministic)
}
func (m *Wildcard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wildcard.Merge(m, src)
}
func (m *Wildcard) XXX_Size() int {
	return xxx_messageInfo_Wildcard.Size(m)
}
func (m *Wildcard) XXX_DiscardUnknown() {
	xxx_messageInfo_Wildcard.DiscardUnknown(m)
}

var xxx_messageInfo_Wildcard proto.InternalMessageInfo

func (m *Wildcard) GetWildcard() string {
	if m != nil {
		return m.Wildcard
	}
	return ""
}

func (m *Wildcard) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type GeoDistance struct {
	Lon                  float32  `protobuf:"fixed32,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Distance             string   `protobuf:"bytes,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Field                string   `protobuf:"bytes,4,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeoDistance) Reset()         { *m = GeoDistance{} }
func (m *GeoDistance) String() string { return proto.CompactTextString(m) }
func (*GeoDistance) ProtoMessage()    {}
func (*GeoDistance) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{37}
}

func (m *GeoDistance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoDistance.Unmarshal(m, b)
}
func (m *GeoDistance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoDistance.Marshal(b, m, deterministic)
}
func (m *GeoDistance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoDistance.Merge(m, src)
}
func (m *GeoDistance) XXX_Size() int {
	return xxx_messageInfo_GeoDistance.Size(m)
}
func (m *GeoDistance) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoDistance.DiscardUnknown(m)
}

var xxx_messageInfo_GeoDistance proto.InternalMessageInfo

func (m *GeoDistance) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *GeoDistance) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *GeoDistance) GetDistance() string {
	if m != nil {
		return m.Distance
	}
	return ""
}

func (m *GeoDistance) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type GlobalSearchInput struct {
	Namespace        []byte   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Size             int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	From             int32    `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	Score            string   `protobuf:"bytes,4,opt,name=score,proto3" json:"score,omitempty"`
	Explain          bool     `protobuf:"varint,5,opt,name=explain,proto3" json:"explain,omitempty"`
	IncludeLocations bool     `protobuf:"varint,6,opt,name=includeLocations,proto3" json:"includeLocations,omitempty"`
	Fields           []string `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty"`
	Sort             []string `protobuf:"bytes,8,rep,name=sort,proto3" json:"sort,omitempty"`
	SearchAfter      []string `protobuf:"bytes,9,rep,name=searchAfter,proto3" json:"searchAfter,omitempty"`
	SearchBefore     []string `protobuf:"bytes,10,rep,name=searchBefore,proto3" json:"searchBefore,omitempty"`
	Highlight        bool     `protobuf:"varint,11,opt,name=highlight,proto3" json:"highlight,omitempty"`
	HighlightStyle   string   `protobuf:"bytes,12,opt,name=highlightStyle,proto3" json:"highlightStyle,omitempty"`
	HighlightFields  []string `protobuf:"bytes,13,rep,name=highlightFields,proto3" json:"highlightFields,omitempty"`
	Facets           []*Facet `protobuf:"bytes,14,rep,name=facets,proto3" json:"facets,omitempty"`
	// Types that are valid to be assigned to Query:
	//	*GlobalSearchInput_QueryString
	//	*GlobalSearchInput_Fuzzy
	//	*GlobalSearchInput_Regexp
	//	*GlobalSearchInput_Term
	//	*GlobalSearchInput_MatchPhrase
	//	*GlobalSearchInput_Match
	//	*GlobalSearchInput_Prefix
	//	*GlobalSearchInput_Wildcard
	//	*GlobalSearchInput_GeoDistance
	Query                isGlobalSearchInput_Query `protobuf_oneof:"query"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GlobalSearchInput) Reset()         { *m = GlobalSearchInput{} }
func (m *GlobalSearchInput) String() string { return proto.CompactTextString(m) }
func (*GlobalSearchInput) ProtoMessage()    {}
func (*GlobalSearchInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_388b6a0687b80922, []int{38}
}

func (m *GlobalSearchInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalSearchInput.Unmarshal(m, b)
}
func (m *GlobalSearchInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalSearchInput.Marshal(b, m, deterministic)
}
func (m *GlobalSearchInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalSearchInput.Merge(m, src)
}
func (m *GlobalSearchInput) XXX_Size() int {
	return xxx_messageInfo_GlobalSearchInput.Size(m)
}
func (m *GlobalSearchInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalSearchInput.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalSearchInput proto.InternalMessageInfo

func (m *GlobalSearchInput) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *GlobalSearchInput) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GlobalSearchInput) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *GlobalSearchInput) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func (m *GlobalSearchInput) GetExplain() bool {
	if m != nil {
		return m.Explain
	}
	return false
}

func (m *GlobalSearchInput) GetIncludeLocations() bool {
	if m != nil {
		return m.IncludeLocations
	}
	return false
}

func (m *GlobalSearchInput) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *GlobalSearchInput) GetSort() []string {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *GlobalSearchInput) GetSearchAfter() []string {
	if m != nil {
		return m.SearchAfter
	}
	return nil
}

func (m *GlobalSearchInput) GetSearchBefore() []string {
	if m != nil {
		return m.SearchBefore
	}
	return nil
}

func (m *GlobalSearchInput) GetHighlight() bool {
	if m != nil {
		return m.Highlight
	}
	return false
}

func (m *GlobalSearchInput) GetHighlightStyle() string {
	if m != nil {
		return m.HighlightStyle
	}
	return ""
}

func (m *GlobalSearchInput) GetHighlightFields() []string {
	if m != nil {
		return m.HighlightFields
	}
	return nil
}

func (m *GlobalSearchInput) GetFacets() []*Facet {
	if m != nil {
		return m.Facets
	}
	return nil
}

type isGlobalSearchInput_Query interface {
	isGlobalSearchInput_Query()
}

type GlobalSearchInput_QueryString struct {
	QueryString *QueryString `protobuf:"bytes,21,opt,name=queryString,proto3,oneof"`
}

type GlobalSearchInput_Fuzzy struct {
	Fuzzy *Fuzzy `protobuf:"bytes,22,opt,name=fuzzy,proto3,oneof"`
}

type GlobalSearchInput_Regexp struct {
	Regexp *Regexp `protobuf:"bytes,23,opt,name=regexp,proto3,oneof"`
}

type GlobalSearchInput_Term struct {
	Term *Term `protobuf:"bytes,24,opt,name=term,proto3,oneof"`
}

type GlobalSearchInput_MatchPhrase struct {
	MatchPhrase *MatchPhrase `protobuf:"bytes,25,opt,name=matchPhrase,proto3,oneof"`
}

type GlobalSearchInput_Match struct {
	Match *Match `protobuf:"bytes,26,opt,name=match,proto3,oneof"`
}

type GlobalSearchInput_Prefix struct {
	Prefix *Prefix `protobuf:"bytes,27,opt,name=prefix,proto3,oneof"`
}

type GlobalSearchInput_Wildcard struct {
	Wildcard *Wildcard `protobuf:"bytes,28,opt,name=wildcard,proto3,oneof"`
}

type GlobalSearchInput_GeoDistance struct {
	GeoDistance *GeoDistance `protobuf:"bytes,29,opt,name=geoDistance,proto3,oneof"`
}

func (*GlobalSearchInput_QueryString) isGlobalSearchInput_Query() {}

func (*GlobalSearchInput_Fuzzy) isGlobalSearchInput_Query() {}

func (*GlobalSearchInput_Regexp) isGlobalSearchInput_Query() {}

func (*GlobalSearchInput_Term) isGlobalSearchInput_Query() {}

func (*GlobalSearchInput_MatchPhrase) isGlobalSearchInput_Query() {}

func (*GlobalSearchInput_Match) isGlobalSearchInput_Query() {}

func (*GlobalSearchInput_Prefix) isGlobalSearchInput_Query() {}

func (*GlobalSearchInput_Wildcard) isGlobalSearchInput_Query() {}

func (*GlobalSearchInput_GeoDistance) isGlobalSearchInput_Query() {}

func (m *GlobalSearchInput) GetQuery() isGlobalSearchInput_Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *GlobalSearchInput) GetQueryString() *QueryString {
	if x, ok := m.GetQuery().(*GlobalSearchInput_QueryString); ok {
		return x.QueryString
	}
	return nil
}

func (m *GlobalSearchInput) GetFuzzy() *Fuzzy {
	if x, ok := m.GetQuery().(*GlobalSearchInput_Fuzzy); ok {
		return x.Fuzzy
	}
	return nil
}

func (m *GlobalSearchInput) GetRegexp() *Regexp {
	if x, ok := m.GetQuery().(*GlobalSearchInput_Regexp); ok {
		return x.Regexp
	}
	return nil
}

func (m *GlobalSearchInput) GetTerm() *Term {
	if x, ok := m.GetQuery().(*GlobalSearchInput_Term); ok {
		return x.Term
	}
	return nil
}

func (m *GlobalSearchInput) GetMatchPhrase() *MatchPhrase {
	if x, ok := m.GetQuery().(*GlobalSearchInput_MatchPhrase); ok {
		return x.MatchPhrase
	}
	return nil
}

func (m *GlobalSearchInput) GetMatch() *Match {
	if x, ok := m.GetQuery().(*GlobalSearchInput_Match); ok {
		return x.Match
	}
	return nil
}

func (m *GlobalSearchInput) GetPrefix() *Prefix {
	if x, ok := m.GetQuery().(*GlobalSearchInput_Prefix); ok {
		return x.Prefix
	}
	return nil
}

func (m *GlobalSearchInput) GetWildcard() *Wildcard {
	if x, ok := m.GetQuery().(*GlobalSearchInput_Wildcard); ok {
		return x.Wildcard
	}
	return nil
}

func (m *GlobalSearchInput) GetGeoDistance() *GeoDistance {
	if x, ok := m.GetQuery().(*GlobalSearchInput_GeoDistance); ok {
		return x.GeoDistance
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GlobalSearchInput) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GlobalSearchInput_QueryString)(nil),
		(*GlobalSearchInput_Fuzzy)(nil),
		(*GlobalSearchInput_Regexp)(nil),
		(*GlobalSearchInput_Term)(nil),
		(*GlobalSearchInput_MatchPhrase)(nil),
		(*GlobalSearchInput_Match)(nil),
		(*GlobalSearchInput_Prefix)(nil),
		(*GlobalSearchInput_Wildcard)(nil),
		(*GlobalSearchInput_GeoDistance)(nil),
	}
}

func init() {
	proto.RegisterEnum("pb.Status", Status_name, Status_value)
	proto.RegisterEnum("pb.IndexFieldType", IndexFieldType_name, IndexFieldType_value)
	proto.RegisterEnum("pb.Action", Action_name, Action_value)
	proto.RegisterEnum("pb.UserType", UserType_name, UserType_value)
	proto.RegisterType((*StateSnapshot)(nil), "pb.StateSnapshot")
	proto.RegisterType((*StateEntry)(nil), "pb.StateEntry")
	proto.RegisterType((*Transaction)(nil), "pb.Transaction")
	proto.RegisterType((*TransactionResponse)(nil), "pb.TransactionResponse")
	proto.RegisterType((*Proposal)(nil), "pb.Proposal")
	proto.RegisterType((*ProposalResponse)(nil), "pb.ProposalResponse")
	proto.RegisterType((*AppliedIndexQuery)(nil), "pb.AppliedIndexQuery")
	proto.RegisterType((*IndexField)(nil), "pb.IndexField")
	proto.RegisterType((*IndexDocument)(nil), "pb.IndexDocument")
	proto.RegisterType((*IndexMeta)(nil), "pb.IndexMeta")
	proto.RegisterType((*IndexMetaList)(nil), "pb.IndexMetaList")
	proto.RegisterType((*IndexMetaPayload)(nil), "pb.IndexMetaPayload")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*UserList)(nil), "pb.UserList")
	proto.RegisterType((*UsernameList)(nil), "pb.UsernameList")
	proto.RegisterType((*UserPayload)(nil), "pb.UserPayload")
	proto.RegisterType((*AccessControl)(nil), "pb.AccessControl")
	proto.RegisterType((*AccessControlList)(nil), "pb.AccessControlList")
	proto.RegisterType((*AccessControlPayload)(nil), "pb.AccessControlPayload")
	proto.RegisterType((*SearchInput)(nil), "pb.SearchInput")
	proto.RegisterType((*IterateInput)(nil), "pb.IterateInput")
	proto.RegisterType((*RetrieveInput)(nil), "pb.RetrieveInput")
	proto.RegisterType((*GlobalIterateInput)(nil), "pb.GlobalIterateInput")
	proto.RegisterType((*GlobalRetrieveInput)(nil), "pb.GlobalRetrieveInput")
	proto.RegisterType((*GlobalDeleteInput)(nil), "pb.GlobalDeleteInput")
	proto.RegisterType((*StateEntryResponse)(nil), "pb.StateEntryResponse")
	proto.RegisterType((*DateTimeRangeFacet)(nil), "pb.DateTimeRangeFacet")
	proto.RegisterType((*NumericRangeFacet)(nil), "pb.NumericRangeFacet")
	proto.RegisterType((*Facet)(nil), "pb.Facet")
	proto.RegisterType((*QueryString)(nil), "pb.QueryString")
	proto.RegisterType((*Fuzzy)(nil), "pb.Fuzzy")
	proto.RegisterType((*Regexp)(nil), "pb.Regexp")
	proto.RegisterType((*Term)(nil), "pb.Term")
	proto.RegisterType((*MatchPhrase)(nil), "pb.MatchPhrase")
	proto.RegisterType((*Match)(nil), "pb.Match")
	proto.RegisterType((*Prefix)(nil), "pb.Prefix")
	proto.RegisterType((*Wildcard)(nil), "pb.Wildcard")
	proto.RegisterType((*GeoDistance)(nil), "pb.GeoDistance")
	proto.RegisterType((*GlobalSearchInput)(nil), "pb.GlobalSearchInput")
}

func init() { proto.RegisterFile("flamed.proto", fileDescriptor_388b6a0687b80922) }

var fileDescriptor_388b6a0687b80922 = []byte{
	// 2108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xcd, 0x6e, 0xdc, 0xc8,
	0x11, 0x16, 0xe7, 0x4f, 0x33, 0x35, 0x33, 0x32, 0xd5, 0x6b, 0x7b, 0x99, 0x5d, 0x67, 0x61, 0x13,
	0xc6, 0xc2, 0xd0, 0x02, 0xc6, 0xc2, 0x0a, 0xbc, 0x40, 0x90, 0x60, 0x31, 0x96, 0x28, 0x6b, 0xb2,
	0xfa, 0xdb, 0xd6, 0xc8, 0xc9, 0xcd, 0x68, 0x93, 0x2d, 0x89, 0x00, 0x87, 0x1c, 0x93, 0x3d, 0xb6,
	0x47, 0xf7, 0xe4, 0x90, 0x9c, 0xf2, 0x18, 0x39, 0x06, 0xc8, 0x03, 0xe4, 0x05, 0x02, 0x04, 0x48,
	0x90, 0x07, 0x08, 0x90, 0xf7, 0x08, 0xaa, 0xba, 0xf9, 0x37, 0x1a, 0xd9, 0x6b, 0x20, 0xd8, 0xdc,
	0xba, 0xbe, 0xaa, 0xee, 0xae, 0x9f, 0xae, 0x62, 0x15, 0x61, 0x70, 0x1e, 0x89, 0xa9, 0x0c, 0x1e,
	0xcf, 0xd2, 0x44, 0x25, 0xac, 0x31, 0x7b, 0xe5, 0xfe, 0x12, 0x86, 0xa7, 0x4a, 0x28, 0x79, 0x1a,
	0x8b, 0x59, 0x76, 0x99, 0x28, 0xe6, 0xc0, 0xba, 0x08, 0x82, 0x54, 0x66, 0x99, 0x63, 0xdd, 0xb7,
	0x1e, 0x0d, 0x78, 0x4e, 0x32, 0x06, 0xad, 0x40, 0x28, 0xe1, 0x34, 0x08, 0xa6, 0xb5, 0xfb, 0x7b,
	0x0b, 0x80, 0xf6, 0x7b, 0xb1, 0x4a, 0x17, 0xb8, 0x79, 0x26, 0x16, 0x51, 0x22, 0x82, 0x7c, 0xb3,
	0x21, 0xd9, 0x3d, 0xe8, 0xc5, 0x62, 0x2a, 0xb3, 0x99, 0xf0, 0xa5, 0x39, 0xa1, 0x04, 0xd8, 0x17,
	0x00, 0xe7, 0x62, 0x1a, 0x46, 0x8b, 0x23, 0x31, 0x95, 0x4e, 0xf3, 0xbe, 0xf5, 0xa8, 0xc7, 0x2b,
	0x08, 0x7b, 0x08, 0x43, 0x4d, 0xbd, 0x90, 0x69, 0x16, 0x26, 0xb1, 0xd3, 0x22, 0x91, 0x3a, 0xe8,
	0xfe, 0xc1, 0x82, 0xfe, 0x24, 0x15, 0x71, 0x26, 0x7c, 0x15, 0x26, 0xf1, 0xff, 0x59, 0x9b, 0xff,
	0x58, 0xf0, 0x49, 0x45, 0x1b, 0x2e, 0xb3, 0x59, 0x12, 0x67, 0x92, 0xb9, 0xd0, 0xc9, 0x94, 0x50,
	0x73, 0xed, 0xdf, 0x8d, 0x27, 0xf0, 0x78, 0xf6, 0xea, 0xf1, 0x29, 0x21, 0xdc, 0x70, 0x50, 0x3f,
	0x99, 0xa6, 0x49, 0xba, 0x93, 0x04, 0x5a, 0xbf, 0x21, 0x2f, 0x81, 0x82, 0x3b, 0x91, 0xef, 0x94,
	0x51, 0xaf, 0x04, 0x96, 0xb4, 0x6f, 0x7d, 0x58, 0xfb, 0xf6, 0x0a, 0xed, 0xd9, 0x23, 0xb8, 0x95,
	0x1a, 0x8d, 0x0f, 0x65, 0x96, 0x89, 0x0b, 0xe9, 0x74, 0x48, 0x6e, 0x19, 0x76, 0x7f, 0x6b, 0x41,
	0xf7, 0x24, 0x4d, 0x66, 0x49, 0x26, 0x22, 0x7c, 0x23, 0xf3, 0x79, 0x98, 0xfb, 0x9b, 0xd6, 0x88,
	0x4d, 0x65, 0xf9, 0x6e, 0x70, 0x8d, 0x26, 0xf8, 0xa9, 0x14, 0x4a, 0x06, 0x23, 0x6d, 0x42, 0x8b,
	0x97, 0x00, 0xdb, 0x86, 0x81, 0x2a, 0x3d, 0x97, 0x39, 0xad, 0xfb, 0xcd, 0x47, 0xfd, 0x27, 0xb7,
	0xd0, 0x51, 0x55, 0x8f, 0xd6, 0x84, 0xdc, 0x7f, 0x58, 0x60, 0xe7, 0x7a, 0x14, 0xce, 0x5e, 0xa5,
	0x4f, 0x19, 0x80, 0xc6, 0x0f, 0x0b, 0x40, 0xf3, 0xbd, 0x01, 0x68, 0x2d, 0x07, 0xe0, 0x3b, 0xb8,
	0xad, 0xae, 0xc7, 0x3d, 0x73, 0xda, 0x64, 0xc5, 0xa7, 0xcb, 0x56, 0x18, 0x3e, 0x5f, 0xb9, 0xc9,
	0xfd, 0x06, 0x36, 0x47, 0xb3, 0x59, 0x14, 0xca, 0x60, 0x1c, 0x07, 0xf2, 0xdd, 0xf7, 0x73, 0x99,
	0x2e, 0x98, 0x0b, 0x03, 0x51, 0x01, 0xc9, 0xba, 0x16, 0xaf, 0x61, 0xee, 0xdf, 0x1b, 0x00, 0xb4,
	0xda, 0x0b, 0x65, 0x14, 0xb0, 0x9f, 0xc3, 0x46, 0x58, 0x50, 0x93, 0xc5, 0x4c, 0x9a, 0xd7, 0xc7,
	0x50, 0x9d, 0x71, 0x8d, 0xc3, 0x97, 0x24, 0xd1, 0x89, 0x98, 0x1c, 0xe4, 0xae, 0x1e, 0xa7, 0x35,
	0xfb, 0x0c, 0xba, 0x22, 0x16, 0xd1, 0xe2, 0x4a, 0xa6, 0xe6, 0x09, 0x16, 0x34, 0xe6, 0x9d, 0x8c,
	0xc5, 0xab, 0x48, 0x06, 0xe4, 0x9c, 0x2e, 0xcf, 0x49, 0x76, 0x1b, 0xda, 0x74, 0x36, 0xbd, 0xb9,
	0x2e, 0xd7, 0x04, 0xa2, 0x99, 0x4a, 0x52, 0xfd, 0xc2, 0xba, 0x5c, 0x13, 0xec, 0x31, 0xb0, 0x30,
	0xf6, 0xa3, 0x79, 0x20, 0x27, 0x32, 0x9d, 0xbe, 0x90, 0xbe, 0x4a, 0xd2, 0xcc, 0x59, 0x27, 0x91,
	0x15, 0x1c, 0x74, 0x8a, 0x41, 0xc7, 0xf1, 0x28, 0x8a, 0x9c, 0x2e, 0x49, 0xd6, 0x30, 0x0c, 0x5c,
	0x90, 0xf8, 0x2f, 0x44, 0x34, 0x97, 0x99, 0xd3, 0x23, 0x81, 0x12, 0xc0, 0xcc, 0x09, 0x84, 0x92,
	0x7b, 0x49, 0x3a, 0x15, 0xca, 0x01, 0x9d, 0x39, 0x25, 0xe2, 0xfe, 0xc9, 0x82, 0x21, 0xb9, 0x6a,
	0x37, 0xf1, 0xe7, 0x53, 0x19, 0xab, 0xc2, 0x33, 0x56, 0xc5, 0x33, 0x15, 0xeb, 0x1b, 0x75, 0xeb,
	0x1d, 0x58, 0x0f, 0xe4, 0xb9, 0x98, 0x47, 0xfa, 0xc9, 0x77, 0x79, 0x4e, 0x12, 0x67, 0x11, 0x8b,
	0x69, 0xe8, 0xe7, 0x1e, 0x33, 0x24, 0x7b, 0x5a, 0x8d, 0xdb, 0x41, 0x98, 0x29, 0xf3, 0x8c, 0x36,
	0xea, 0x71, 0xe3, 0x4b, 0x52, 0xee, 0x3f, 0x5b, 0xd0, 0x23, 0xf6, 0xa1, 0x49, 0xb7, 0xb2, 0xde,
	0x59, 0xcb, 0xf5, 0xce, 0x81, 0xf5, 0x37, 0xa6, 0x16, 0x34, 0xe8, 0x25, 0xe5, 0x64, 0xd5, 0x96,
	0xe6, 0x8d, 0xb6, 0xb4, 0xea, 0xb6, 0x50, 0x1c, 0xd0, 0x49, 0xc6, 0xa0, 0x76, 0x1e, 0x87, 0x12,
	0x43, 0x19, 0x0a, 0x72, 0x2e, 0xa3, 0x03, 0x5f, 0xc3, 0xd8, 0x16, 0xd8, 0x45, 0x68, 0x72, 0x39,
	0x1d, 0xfd, 0x6b, 0x38, 0xbb, 0x0f, 0x7d, 0x73, 0x3d, 0x3d, 0xed, 0x2e, 0x85, 0xa3, 0x0a, 0x61,
	0x3d, 0x33, 0xe4, 0x28, 0x7f, 0xb6, 0x3d, 0x5d, 0xcf, 0x96, 0x60, 0xf6, 0x33, 0xb8, 0x63, 0xa0,
	0x5d, 0xa1, 0xe4, 0x24, 0x9c, 0xca, 0x13, 0x91, 0x66, 0x32, 0x35, 0x0f, 0x62, 0x35, 0x13, 0x2d,
	0x32, 0x0c, 0x8a, 0x81, 0xd3, 0x27, 0xe1, 0x1a, 0x86, 0x51, 0x50, 0x8b, 0x99, 0xd4, 0x02, 0x03,
	0x5d, 0x36, 0x0a, 0x80, 0x7d, 0x09, 0x1b, 0xfe, 0x3c, 0x53, 0xc9, 0x94, 0x34, 0xc9, 0xc2, 0xcc,
	0x19, 0x92, 0xc8, 0x12, 0x5a, 0x2f, 0x9d, 0x1b, 0xcb, 0xa5, 0xf3, 0x1e, 0xf4, 0xe6, 0xb3, 0xc0,
	0x70, 0x6f, 0x69, 0x6e, 0x01, 0xb0, 0x6f, 0x61, 0x33, 0xac, 0x3e, 0x60, 0x7a, 0x50, 0x36, 0x3d,
	0xa8, 0xcd, 0xe2, 0x41, 0xe5, 0x4c, 0x7e, 0x5d, 0xd6, 0xdd, 0x35, 0x19, 0x80, 0xaf, 0x0a, 0x01,
	0xb6, 0x0d, 0xc3, 0xb0, 0x0a, 0x38, 0x16, 0x9d, 0x36, 0x2c, 0x4e, 0x43, 0x06, 0xaf, 0xcb, 0xb8,
	0x3e, 0xd8, 0x05, 0xef, 0xc4, 0x7c, 0x92, 0x5d, 0xe8, 0xe8, 0xda, 0x57, 0xfd, 0x2c, 0x8e, 0x74,
	0x35, 0x34, 0x1c, 0xf6, 0x15, 0xf4, 0x8a, 0x83, 0xe8, 0xa9, 0x5e, 0xbb, 0xa8, 0xe4, 0xbb, 0xff,
	0xb6, 0xa0, 0x75, 0x86, 0xa1, 0x79, 0x04, 0xdd, 0x79, 0x26, 0xd3, 0x4a, 0xd1, 0x1b, 0xe0, 0xa6,
	0x33, 0x83, 0xf1, 0x82, 0x8b, 0x85, 0x28, 0x4d, 0x22, 0x99, 0x99, 0x4a, 0xa7, 0x09, 0x2c, 0x75,
	0x28, 0x11, 0x97, 0xcd, 0x40, 0x41, 0x23, 0x6f, 0x26, 0xb2, 0xec, 0x6d, 0x92, 0x06, 0xe6, 0x43,
	0x50, 0xd0, 0xf5, 0x40, 0xb5, 0xdf, 0x1b, 0xa8, 0xce, 0x72, 0xa0, 0xf2, 0x5e, 0x6b, 0xbd, 0xec,
	0xb5, 0x8a, 0xef, 0x68, 0xb7, 0xfc, 0x8e, 0xba, 0x5f, 0x43, 0x17, 0xed, 0xa0, 0x50, 0x3c, 0xd4,
	0x7a, 0x56, 0xa2, 0xd0, 0xcd, 0xed, 0xe4, 0x05, 0xc7, 0x7d, 0x02, 0x83, 0x33, 0xa3, 0x3d, 0xed,
	0x72, 0x61, 0x30, 0xaf, 0xd0, 0xb4, 0xb3, 0xc7, 0x6b, 0x98, 0x7b, 0x0c, 0x7d, 0xdc, 0xf3, 0x31,
	0xa1, 0xba, 0x07, 0x2d, 0x3c, 0xc2, 0x44, 0xa9, 0x54, 0x84, 0x50, 0xf7, 0x6f, 0x16, 0x0c, 0x47,
	0xbe, 0x2f, 0xb3, 0x6c, 0x27, 0x89, 0x55, 0x9a, 0x44, 0x35, 0x27, 0x5b, 0x4b, 0x4e, 0xfe, 0x60,
	0xb7, 0x36, 0x93, 0xe9, 0x34, 0xcc, 0xa8, 0x80, 0x61, 0x80, 0x3a, 0xbc, 0x82, 0xd4, 0xc3, 0xd0,
	0x7a, 0x6f, 0x18, 0xda, 0x37, 0x85, 0xa1, 0xb3, 0x22, 0x0c, 0xeb, 0x95, 0x30, 0x4c, 0x60, 0xb3,
	0x66, 0x0e, 0x79, 0xf6, 0x5b, 0xd8, 0x14, 0xcb, 0xa0, 0x09, 0xcc, 0xa6, 0xf6, 0x58, 0x85, 0xc9,
	0xaf, 0xcb, 0xba, 0x19, 0xdc, 0xae, 0xc9, 0x7c, 0x8c, 0xff, 0xbf, 0x81, 0x61, 0xed, 0x40, 0x13,
	0x88, 0x15, 0x17, 0xd7, 0xe5, 0xdc, 0x3f, 0x5b, 0xd0, 0x3f, 0x95, 0x22, 0xf5, 0x2f, 0xc7, 0xf1,
	0x6c, 0xae, 0x3e, 0xf0, 0xe9, 0xa8, 0x37, 0x9b, 0x8d, 0x0f, 0x37, 0x9b, 0xcd, 0x55, 0xcd, 0xe6,
	0x6d, 0x68, 0xbf, 0xc6, 0xc6, 0x86, 0xc2, 0x33, 0xe0, 0x9a, 0x40, 0x47, 0x9f, 0xa7, 0xc9, 0xd4,
	0x44, 0x85, 0xd6, 0x28, 0x19, 0x85, 0xd3, 0x30, 0xcf, 0x18, 0x4d, 0xb8, 0x7f, 0xb1, 0x60, 0x30,
	0x56, 0x32, 0x15, 0x4a, 0xfe, 0x78, 0x4a, 0xe7, 0xea, 0x69, 0x9d, 0xb5, 0x7a, 0x77, 0xa1, 0x33,
	0x4b, 0xe5, 0x79, 0xa8, 0x1b, 0x9c, 0x01, 0x37, 0xd4, 0x0d, 0x6a, 0xff, 0xd1, 0x82, 0x21, 0x97,
	0x2a, 0x0d, 0xe5, 0x9b, 0x1f, 0x51, 0xef, 0x7b, 0xd0, 0x33, 0x13, 0x9d, 0xd4, 0x9d, 0xf5, 0x80,
	0x97, 0x80, 0xab, 0x80, 0x3d, 0x8f, 0x92, 0x57, 0x22, 0xfa, 0x08, 0x7f, 0xe6, 0x9e, 0x68, 0xac,
	0xf4, 0x44, 0x73, 0xb5, 0x27, 0x5a, 0x55, 0x4f, 0x7c, 0x0f, 0x9f, 0xe8, 0x5b, 0x3f, 0xc6, 0x1d,
	0x35, 0x43, 0x1a, 0xcb, 0x86, 0x1c, 0xc3, 0xa6, 0x3e, 0x72, 0x57, 0x46, 0x52, 0xfd, 0x0f, 0x0e,
	0xfc, 0x9d, 0x05, 0xac, 0x1c, 0x75, 0x8b, 0x09, 0xe3, 0x4b, 0xd8, 0xc0, 0x99, 0x41, 0x8e, 0xde,
	0x88, 0x30, 0xc2, 0xde, 0x88, 0xce, 0xed, 0xf2, 0x25, 0xb4, 0x3a, 0x57, 0xeb, 0xc8, 0x15, 0x73,
	0xf5, 0x63, 0x80, 0xac, 0x38, 0x97, 0xdc, 0x65, 0xda, 0xbb, 0xca, 0x6d, 0x15, 0x09, 0xf7, 0x04,
	0x58, 0xde, 0x7c, 0x70, 0x11, 0x5f, 0xc8, 0x3d, 0xe1, 0xcb, 0xd5, 0xad, 0x28, 0x35, 0xd6, 0x22,
	0x55, 0xf9, 0xf7, 0x8c, 0x08, 0x66, 0x43, 0x53, 0xc6, 0x81, 0x79, 0x1c, 0xb8, 0x74, 0xbf, 0x83,
	0xcd, 0xa3, 0xf9, 0x54, 0xa6, 0xa1, 0xff, 0x81, 0x03, 0x6d, 0x68, 0x4e, 0x43, 0xdd, 0x25, 0x5a,
	0x1c, 0x97, 0x84, 0x08, 0x1d, 0x64, 0x44, 0xc4, 0x3b, 0xf7, 0x5f, 0x16, 0xb4, 0xdf, 0xab, 0xd2,
	0x39, 0xf5, 0x3f, 0x46, 0x25, 0x22, 0x50, 0x32, 0x0b, 0xaf, 0xf4, 0xe7, 0xb5, 0xcd, 0x69, 0xcd,
	0xf6, 0xe1, 0x93, 0xe0, 0x9a, 0x99, 0xf9, 0x2c, 0x78, 0x17, 0xfd, 0x73, 0xdd, 0x0b, 0x7c, 0xd5,
	0x16, 0xe6, 0x01, 0x8b, 0x97, 0xcd, 0xcb, 0xc7, 0xb1, 0x3b, 0x78, 0xd0, 0x35, 0xe3, 0xf9, 0x8a,
	0x0d, 0xee, 0xe7, 0xd0, 0xa7, 0xf1, 0xeb, 0x54, 0xa5, 0x61, 0x7c, 0xc1, 0x06, 0x60, 0xbd, 0x36,
	0xa6, 0x59, 0xaf, 0xdd, 0x0c, 0xda, 0x7b, 0xf3, 0xab, 0x2b, 0xaa, 0x5a, 0x4a, 0xa6, 0xd3, 0xdc,
	0x68, 0x5c, 0xe3, 0xc3, 0x3a, 0x9f, 0x5f, 0x5d, 0x85, 0x71, 0x1e, 0xfd, 0x36, 0x2f, 0x81, 0xd2,
	0x25, 0xcd, 0xaa, 0x4b, 0x5c, 0x18, 0xe8, 0x94, 0x39, 0x90, 0xf1, 0x85, 0xba, 0x34, 0xdd, 0x45,
	0x0d, 0x73, 0x9f, 0x42, 0x87, 0xcb, 0x0b, 0xf9, 0x6e, 0x86, 0xe9, 0x96, 0xd2, 0xca, 0xdc, 0x6b,
	0xa8, 0xd5, 0xee, 0x76, 0xbf, 0x86, 0x16, 0x4e, 0x4e, 0x2b, 0x75, 0x5d, 0xbd, 0xc3, 0x83, 0xfe,
	0xa1, 0x50, 0xfe, 0xe5, 0xc9, 0x65, 0x2a, 0x32, 0x89, 0xfd, 0xf6, 0xb4, 0x24, 0xcd, 0xfe, 0x2a,
	0x74, 0xc3, 0x31, 0xdb, 0xd0, 0xa6, 0x63, 0x90, 0x4d, 0xd2, 0x66, 0xab, 0x26, 0x6e, 0xd8, 0xf4,
	0x14, 0x3a, 0x27, 0xba, 0x78, 0x94, 0x45, 0xc5, 0x58, 0x59, 0x16, 0x95, 0x15, 0xfb, 0x7e, 0x01,
	0xdd, 0x5f, 0x87, 0x51, 0xe0, 0x8b, 0x34, 0xc0, 0xf6, 0xe2, 0xad, 0x59, 0xe7, 0xed, 0x45, 0x4e,
	0xdf, 0xb0, 0xdb, 0x87, 0xfe, 0x73, 0x99, 0xec, 0x86, 0x99, 0x12, 0xb1, 0x4f, 0x2f, 0x3f, 0x32,
	0x1f, 0xdc, 0x06, 0xc7, 0x25, 0x21, 0x42, 0xa7, 0x16, 0x22, 0x42, 0xe1, 0x25, 0x81, 0x91, 0xcf,
	0x1b, 0xc5, 0x9c, 0x2e, 0x2f, 0x69, 0x55, 0x2f, 0xf9, 0x6b, 0x27, 0xaf, 0x52, 0x3f, 0xfc, 0x93,
	0x9b, 0xe7, 0x4a, 0xa3, 0x92, 0x2b, 0x79, 0x05, 0x36, 0xf9, 0x93, 0x7f, 0x2a, 0x33, 0x1f, 0xa7,
	0x6a, 0x73, 0x23, 0x11, 0x34, 0xd1, 0xbd, 0x9b, 0x45, 0x22, 0x8c, 0xcd, 0x60, 0x96, 0x93, 0x38,
	0x6f, 0x99, 0x59, 0xf9, 0x20, 0xf1, 0x85, 0xfe, 0xf1, 0xa2, 0xe7, 0xb2, 0x6b, 0x38, 0x06, 0x82,
	0x0c, 0xc0, 0x79, 0x1c, 0xdb, 0x45, 0x43, 0x91, 0x6e, 0x49, 0xaa, 0x9c, 0x2e, 0xa1, 0xb4, 0xc6,
	0xb7, 0x92, 0x91, 0x71, 0xa3, 0x73, 0x45, 0x53, 0x17, 0xb2, 0xaa, 0x10, 0x4d, 0x83, 0x44, 0x3e,
	0x93, 0xe7, 0xa8, 0x30, 0xe8, 0x16, 0xb4, 0x8a, 0xa1, 0x4f, 0x2e, 0xc3, 0x8b, 0xcb, 0x28, 0xbc,
	0xb8, 0x54, 0x34, 0x5c, 0x75, 0x79, 0x09, 0x60, 0x11, 0x2e, 0x88, 0x53, 0xb5, 0x88, 0xa4, 0x19,
	0xaf, 0x96, 0x50, 0x9c, 0x02, 0x0b, 0x64, 0x4f, 0x1b, 0x30, 0xa4, 0xcb, 0x96, 0x61, 0xf6, 0x00,
	0x3a, 0xe7, 0xba, 0x4e, 0x6c, 0x50, 0x9d, 0xe8, 0x61, 0x9d, 0xd0, 0xb5, 0xc1, 0x30, 0xd8, 0x36,
	0xf4, 0x5f, 0x97, 0xf5, 0xc0, 0xb9, 0x43, 0x85, 0x9b, 0x7e, 0x52, 0x55, 0xca, 0xc4, 0xfe, 0x1a,
	0xaf, 0x4a, 0xb1, 0x07, 0xd0, 0xc6, 0xcc, 0x5f, 0x38, 0x77, 0x49, 0x5c, 0x1f, 0x8b, 0xc0, 0xfe,
	0x1a, 0xd7, 0x1c, 0xf6, 0xb0, 0xc8, 0xe5, 0x4f, 0x49, 0x86, 0xda, 0x3b, 0x9d, 0xe7, 0xfb, 0x6b,
	0x45, 0x66, 0x7f, 0x61, 0x72, 0xd7, 0x29, 0x1b, 0x6c, 0xcc, 0xe9, 0xfd, 0x35, 0x93, 0xc7, 0xdb,
	0xf5, 0x14, 0xfd, 0x49, 0xa9, 0x5d, 0x25, 0x91, 0x51, 0xbb, 0x6a, 0xd6, 0x3e, 0xc8, 0xd3, 0xf2,
	0xb3, 0x52, 0x3b, 0x12, 0x47, 0xed, 0x74, 0x8e, 0x3e, 0x2c, 0x72, 0xf0, 0xf3, 0x52, 0x3b, 0x9d,
	0x9f, 0xa8, 0x9d, 0xc9, 0xc8, 0xad, 0x4a, 0xbe, 0xdd, 0x23, 0x39, 0x9a, 0xb9, 0xf2, 0x7c, 0xdc,
	0x5f, 0xab, 0xe4, 0xdf, 0x36, 0xf4, 0x2f, 0xca, 0x4c, 0x73, 0x7e, 0x5a, 0x6a, 0x5a, 0x49, 0x40,
	0xd4, 0xb4, 0x22, 0xf5, 0x6c, 0xdd, 0xb4, 0x8c, 0x5b, 0x0f, 0xa1, 0xa3, 0xff, 0xdd, 0xb1, 0x01,
	0x74, 0xb9, 0xf7, 0x2b, 0x6f, 0x67, 0xe2, 0xed, 0xda, 0x6b, 0x48, 0x8d, 0x76, 0x76, 0xbc, 0x13,
	0xa4, 0xac, 0x2d, 0x0e, 0x1b, 0xf5, 0x9f, 0x5c, 0xac, 0x0b, 0xad, 0x89, 0xf7, 0x9b, 0x89, 0xbd,
	0xc6, 0xfa, 0xb0, 0x7e, 0x74, 0x76, 0xe8, 0xf1, 0xf1, 0x8e, 0x6d, 0x21, 0xf1, 0xec, 0xf8, 0xf8,
	0xc0, 0x1b, 0x1d, 0xd9, 0x0d, 0x36, 0x84, 0xde, 0x73, 0xef, 0xf8, 0xe5, 0xc9, 0xf1, 0xf8, 0x68,
	0x62, 0x37, 0x91, 0xdc, 0x1d, 0x4d, 0xbc, 0x97, 0x93, 0xf1, 0xa1, 0x67, 0xb7, 0xb6, 0xde, 0x42,
	0x47, 0x37, 0xdd, 0xfa, 0xe6, 0x09, 0x1f, 0x7b, 0x2f, 0x3c, 0x7b, 0x8d, 0x01, 0x74, 0x4e, 0xbd,
	0x11, 0xdf, 0xd9, 0xd7, 0xc7, 0x8d, 0x27, 0x1e, 0x1f, 0x4d, 0x3c, 0xbb, 0xc1, 0x7a, 0xd0, 0x3e,
	0xf4, 0xf8, 0x73, 0xcf, 0x6e, 0xa2, 0xcc, 0xf8, 0xe8, 0xd4, 0xe3, 0x13, 0xbb, 0x85, 0xeb, 0xb3,
	0x13, 0x3c, 0xd8, 0x6e, 0xeb, 0x35, 0xe1, 0x1d, 0x5c, 0xef, 0x7a, 0x07, 0xde, 0xc4, 0xb3, 0xd7,
	0xf1, 0x9c, 0x5d, 0x6f, 0x6f, 0x74, 0x76, 0x30, 0xb1, 0xbb, 0x5b, 0x5f, 0xe9, 0xa1, 0x8f, 0xcc,
	0xd8, 0x00, 0x38, 0x3d, 0x3b, 0xf1, 0xf8, 0xcb, 0xb3, 0x53, 0x8f, 0xdb, 0x6b, 0xec, 0x16, 0xf4,
	0x8f, 0x8e, 0xf9, 0xe1, 0xe8, 0x40, 0x03, 0xd6, 0xab, 0x0e, 0xfd, 0xeb, 0xdf, 0xfe, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xd7, 0x36, 0x0c, 0x7f, 0xfb, 0x17, 0x00, 0x00,
}
