// Code generated by protoc-gen-go. DO NOT EDIT.
// source: odsm.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FlameAction_FlameActionType int32

const (
	FlameAction_CREATE FlameAction_FlameActionType = 0
	FlameAction_UPDATE FlameAction_FlameActionType = 1
	FlameAction_DELETE FlameAction_FlameActionType = 2
	FlameAction_APPEND FlameAction_FlameActionType = 3
)

var FlameAction_FlameActionType_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
	3: "APPEND",
}

var FlameAction_FlameActionType_value = map[string]int32{
	"CREATE": 0,
	"UPDATE": 1,
	"DELETE": 2,
	"APPEND": 3,
}

func (x FlameAction_FlameActionType) String() string {
	return proto.EnumName(FlameAction_FlameActionType_name, int32(x))
}

func (FlameAction_FlameActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{1, 0}
}

type FlameIndexField_FlameIndexFieldType int32

const (
	FlameIndexField_TEXT      FlameIndexField_FlameIndexFieldType = 0
	FlameIndexField_NUMERIC   FlameIndexField_FlameIndexFieldType = 1
	FlameIndexField_BOOLEAN   FlameIndexField_FlameIndexFieldType = 2
	FlameIndexField_GEO_POINT FlameIndexField_FlameIndexFieldType = 3
	FlameIndexField_DATE_TIME FlameIndexField_FlameIndexFieldType = 4
)

var FlameIndexField_FlameIndexFieldType_name = map[int32]string{
	0: "TEXT",
	1: "NUMERIC",
	2: "BOOLEAN",
	3: "GEO_POINT",
	4: "DATE_TIME",
}

var FlameIndexField_FlameIndexFieldType_value = map[string]int32{
	"TEXT":      0,
	"NUMERIC":   1,
	"BOOLEAN":   2,
	"GEO_POINT": 3,
	"DATE_TIME": 4,
}

func (x FlameIndexField_FlameIndexFieldType) String() string {
	return proto.EnumName(FlameIndexField_FlameIndexFieldType_name, int32(x))
}

func (FlameIndexField_FlameIndexFieldType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{4, 0}
}

type FlameUser_FlameUserType int32

const (
	FlameUser_SUPER_USER  FlameUser_FlameUserType = 0
	FlameUser_NORMAL_USER FlameUser_FlameUserType = 1
)

var FlameUser_FlameUserType_name = map[int32]string{
	0: "SUPER_USER",
	1: "NORMAL_USER",
}

var FlameUser_FlameUserType_value = map[string]int32{
	"SUPER_USER":  0,
	"NORMAL_USER": 1,
}

func (x FlameUser_FlameUserType) String() string {
	return proto.EnumName(FlameUser_FlameUserType_name, int32(x))
}

func (FlameUser_FlameUserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{9, 0}
}

type FlameProposal_FlameProposalType int32

const (
	FlameProposal_BATCH_ACTION          FlameProposal_FlameProposalType = 0
	FlameProposal_CREATE_USER           FlameProposal_FlameProposalType = 1
	FlameProposal_UPDATE_USER           FlameProposal_FlameProposalType = 2
	FlameProposal_DELETE_USER           FlameProposal_FlameProposalType = 3
	FlameProposal_CREATE_INDEX_META     FlameProposal_FlameProposalType = 4
	FlameProposal_UPDATE_INDEX_META     FlameProposal_FlameProposalType = 5
	FlameProposal_DELETE_INDEX_META     FlameProposal_FlameProposalType = 6
	FlameProposal_CREATE_ACCESS_CONTROL FlameProposal_FlameProposalType = 7
	FlameProposal_UPDATE_ACCESS_CONTROL FlameProposal_FlameProposalType = 8
	FlameProposal_DELETE_ACCESS_CONTROL FlameProposal_FlameProposalType = 9
	FlameProposal_BATCH_USER            FlameProposal_FlameProposalType = 10
	FlameProposal_BATCH_INDEX_META      FlameProposal_FlameProposalType = 11
	FlameProposal_BATCH_ACCESS_CONTROL  FlameProposal_FlameProposalType = 12
)

var FlameProposal_FlameProposalType_name = map[int32]string{
	0:  "BATCH_ACTION",
	1:  "CREATE_USER",
	2:  "UPDATE_USER",
	3:  "DELETE_USER",
	4:  "CREATE_INDEX_META",
	5:  "UPDATE_INDEX_META",
	6:  "DELETE_INDEX_META",
	7:  "CREATE_ACCESS_CONTROL",
	8:  "UPDATE_ACCESS_CONTROL",
	9:  "DELETE_ACCESS_CONTROL",
	10: "BATCH_USER",
	11: "BATCH_INDEX_META",
	12: "BATCH_ACCESS_CONTROL",
}

var FlameProposal_FlameProposalType_value = map[string]int32{
	"BATCH_ACTION":          0,
	"CREATE_USER":           1,
	"UPDATE_USER":           2,
	"DELETE_USER":           3,
	"CREATE_INDEX_META":     4,
	"UPDATE_INDEX_META":     5,
	"DELETE_INDEX_META":     6,
	"CREATE_ACCESS_CONTROL": 7,
	"UPDATE_ACCESS_CONTROL": 8,
	"DELETE_ACCESS_CONTROL": 9,
	"BATCH_USER":            10,
	"BATCH_INDEX_META":      11,
	"BATCH_ACCESS_CONTROL":  12,
}

func (x FlameProposal_FlameProposalType) String() string {
	return proto.EnumName(FlameProposal_FlameProposalType_name, int32(x))
}

func (FlameProposal_FlameProposalType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{14, 0}
}

type FlameEntry struct {
	Namespace            []byte   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlameEntry) Reset()         { *m = FlameEntry{} }
func (m *FlameEntry) String() string { return proto.CompactTextString(m) }
func (*FlameEntry) ProtoMessage()    {}
func (*FlameEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{0}
}

func (m *FlameEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameEntry.Unmarshal(m, b)
}
func (m *FlameEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameEntry.Marshal(b, m, deterministic)
}
func (m *FlameEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameEntry.Merge(m, src)
}
func (m *FlameEntry) XXX_Size() int {
	return xxx_messageInfo_FlameEntry.Size(m)
}
func (m *FlameEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FlameEntry proto.InternalMessageInfo

func (m *FlameEntry) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *FlameEntry) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *FlameEntry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type FlameAction struct {
	FlameActionType      FlameAction_FlameActionType `protobuf:"varint,1,opt,name=flameActionType,proto3,enum=pb.FlameAction_FlameActionType" json:"flameActionType,omitempty"`
	FlameEntry           *FlameEntry                 `protobuf:"bytes,2,opt,name=flameEntry,proto3" json:"flameEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *FlameAction) Reset()         { *m = FlameAction{} }
func (m *FlameAction) String() string { return proto.CompactTextString(m) }
func (*FlameAction) ProtoMessage()    {}
func (*FlameAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{1}
}

func (m *FlameAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameAction.Unmarshal(m, b)
}
func (m *FlameAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameAction.Marshal(b, m, deterministic)
}
func (m *FlameAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameAction.Merge(m, src)
}
func (m *FlameAction) XXX_Size() int {
	return xxx_messageInfo_FlameAction.Size(m)
}
func (m *FlameAction) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameAction.DiscardUnknown(m)
}

var xxx_messageInfo_FlameAction proto.InternalMessageInfo

func (m *FlameAction) GetFlameActionType() FlameAction_FlameActionType {
	if m != nil {
		return m.FlameActionType
	}
	return FlameAction_CREATE
}

func (m *FlameAction) GetFlameEntry() *FlameEntry {
	if m != nil {
		return m.FlameEntry
	}
	return nil
}

type FlameBatchAction struct {
	FlameActionList      []*FlameAction `protobuf:"bytes,1,rep,name=flameActionList,proto3" json:"flameActionList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FlameBatchAction) Reset()         { *m = FlameBatchAction{} }
func (m *FlameBatchAction) String() string { return proto.CompactTextString(m) }
func (*FlameBatchAction) ProtoMessage()    {}
func (*FlameBatchAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{2}
}

func (m *FlameBatchAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameBatchAction.Unmarshal(m, b)
}
func (m *FlameBatchAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameBatchAction.Marshal(b, m, deterministic)
}
func (m *FlameBatchAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameBatchAction.Merge(m, src)
}
func (m *FlameBatchAction) XXX_Size() int {
	return xxx_messageInfo_FlameBatchAction.Size(m)
}
func (m *FlameBatchAction) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameBatchAction.DiscardUnknown(m)
}

var xxx_messageInfo_FlameBatchAction proto.InternalMessageInfo

func (m *FlameBatchAction) GetFlameActionList() []*FlameAction {
	if m != nil {
		return m.FlameActionList
	}
	return nil
}

type FlameBatchRead struct {
	FlameEntryList       []*FlameEntry `protobuf:"bytes,1,rep,name=flameEntryList,proto3" json:"flameEntryList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FlameBatchRead) Reset()         { *m = FlameBatchRead{} }
func (m *FlameBatchRead) String() string { return proto.CompactTextString(m) }
func (*FlameBatchRead) ProtoMessage()    {}
func (*FlameBatchRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{3}
}

func (m *FlameBatchRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameBatchRead.Unmarshal(m, b)
}
func (m *FlameBatchRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameBatchRead.Marshal(b, m, deterministic)
}
func (m *FlameBatchRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameBatchRead.Merge(m, src)
}
func (m *FlameBatchRead) XXX_Size() int {
	return xxx_messageInfo_FlameBatchRead.Size(m)
}
func (m *FlameBatchRead) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameBatchRead.DiscardUnknown(m)
}

var xxx_messageInfo_FlameBatchRead proto.InternalMessageInfo

func (m *FlameBatchRead) GetFlameEntryList() []*FlameEntry {
	if m != nil {
		return m.FlameEntryList
	}
	return nil
}

type FlameIndexField struct {
	FlameIndexFieldType  FlameIndexField_FlameIndexFieldType `protobuf:"varint,1,opt,name=flameIndexFieldType,proto3,enum=pb.FlameIndexField_FlameIndexFieldType" json:"flameIndexFieldType,omitempty"`
	Name                 string                              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Analyzer             string                              `protobuf:"bytes,3,opt,name=analyzer,proto3" json:"analyzer,omitempty"`
	Enabled              bool                                `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Index                bool                                `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	Store                bool                                `protobuf:"varint,6,opt,name=store,proto3" json:"store,omitempty"`
	IncludeTermVectors   bool                                `protobuf:"varint,7,opt,name=includeTermVectors,proto3" json:"includeTermVectors,omitempty"`
	IncludeInAll         bool                                `protobuf:"varint,8,opt,name=includeInAll,proto3" json:"includeInAll,omitempty"`
	DocValues            bool                                `protobuf:"varint,9,opt,name=docValues,proto3" json:"docValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *FlameIndexField) Reset()         { *m = FlameIndexField{} }
func (m *FlameIndexField) String() string { return proto.CompactTextString(m) }
func (*FlameIndexField) ProtoMessage()    {}
func (*FlameIndexField) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{4}
}

func (m *FlameIndexField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameIndexField.Unmarshal(m, b)
}
func (m *FlameIndexField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameIndexField.Marshal(b, m, deterministic)
}
func (m *FlameIndexField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameIndexField.Merge(m, src)
}
func (m *FlameIndexField) XXX_Size() int {
	return xxx_messageInfo_FlameIndexField.Size(m)
}
func (m *FlameIndexField) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameIndexField.DiscardUnknown(m)
}

var xxx_messageInfo_FlameIndexField proto.InternalMessageInfo

func (m *FlameIndexField) GetFlameIndexFieldType() FlameIndexField_FlameIndexFieldType {
	if m != nil {
		return m.FlameIndexFieldType
	}
	return FlameIndexField_TEXT
}

func (m *FlameIndexField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FlameIndexField) GetAnalyzer() string {
	if m != nil {
		return m.Analyzer
	}
	return ""
}

func (m *FlameIndexField) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *FlameIndexField) GetIndex() bool {
	if m != nil {
		return m.Index
	}
	return false
}

func (m *FlameIndexField) GetStore() bool {
	if m != nil {
		return m.Store
	}
	return false
}

func (m *FlameIndexField) GetIncludeTermVectors() bool {
	if m != nil {
		return m.IncludeTermVectors
	}
	return false
}

func (m *FlameIndexField) GetIncludeInAll() bool {
	if m != nil {
		return m.IncludeInAll
	}
	return false
}

func (m *FlameIndexField) GetDocValues() bool {
	if m != nil {
		return m.DocValues
	}
	return false
}

type FlameIndexDocument struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Default              bool               `protobuf:"varint,2,opt,name=default,proto3" json:"default,omitempty"`
	FlameIndexFieldList  []*FlameIndexField `protobuf:"bytes,3,rep,name=flameIndexFieldList,proto3" json:"flameIndexFieldList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FlameIndexDocument) Reset()         { *m = FlameIndexDocument{} }
func (m *FlameIndexDocument) String() string { return proto.CompactTextString(m) }
func (*FlameIndexDocument) ProtoMessage()    {}
func (*FlameIndexDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{5}
}

func (m *FlameIndexDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameIndexDocument.Unmarshal(m, b)
}
func (m *FlameIndexDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameIndexDocument.Marshal(b, m, deterministic)
}
func (m *FlameIndexDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameIndexDocument.Merge(m, src)
}
func (m *FlameIndexDocument) XXX_Size() int {
	return xxx_messageInfo_FlameIndexDocument.Size(m)
}
func (m *FlameIndexDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameIndexDocument.DiscardUnknown(m)
}

var xxx_messageInfo_FlameIndexDocument proto.InternalMessageInfo

func (m *FlameIndexDocument) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FlameIndexDocument) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *FlameIndexDocument) GetFlameIndexFieldList() []*FlameIndexField {
	if m != nil {
		return m.FlameIndexFieldList
	}
	return nil
}

type FlameIndexMeta struct {
	Namespace              []byte                `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version                uint32                `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Enabled                bool                  `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Default                bool                  `protobuf:"varint,4,opt,name=default,proto3" json:"default,omitempty"`
	CreatedAt              uint64                `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt              uint64                `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	FlameIndexDocumentList []*FlameIndexDocument `protobuf:"bytes,7,rep,name=flameIndexDocumentList,proto3" json:"flameIndexDocumentList,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}              `json:"-"`
	XXX_unrecognized       []byte                `json:"-"`
	XXX_sizecache          int32                 `json:"-"`
}

func (m *FlameIndexMeta) Reset()         { *m = FlameIndexMeta{} }
func (m *FlameIndexMeta) String() string { return proto.CompactTextString(m) }
func (*FlameIndexMeta) ProtoMessage()    {}
func (*FlameIndexMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{6}
}

func (m *FlameIndexMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameIndexMeta.Unmarshal(m, b)
}
func (m *FlameIndexMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameIndexMeta.Marshal(b, m, deterministic)
}
func (m *FlameIndexMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameIndexMeta.Merge(m, src)
}
func (m *FlameIndexMeta) XXX_Size() int {
	return xxx_messageInfo_FlameIndexMeta.Size(m)
}
func (m *FlameIndexMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameIndexMeta.DiscardUnknown(m)
}

var xxx_messageInfo_FlameIndexMeta proto.InternalMessageInfo

func (m *FlameIndexMeta) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *FlameIndexMeta) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *FlameIndexMeta) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *FlameIndexMeta) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *FlameIndexMeta) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *FlameIndexMeta) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *FlameIndexMeta) GetFlameIndexDocumentList() []*FlameIndexDocument {
	if m != nil {
		return m.FlameIndexDocumentList
	}
	return nil
}

type FlameIndexMetaList struct {
	FlameIndexMetaList   []*FlameIndexMeta `protobuf:"bytes,1,rep,name=flameIndexMetaList,proto3" json:"flameIndexMetaList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FlameIndexMetaList) Reset()         { *m = FlameIndexMetaList{} }
func (m *FlameIndexMetaList) String() string { return proto.CompactTextString(m) }
func (*FlameIndexMetaList) ProtoMessage()    {}
func (*FlameIndexMetaList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{7}
}

func (m *FlameIndexMetaList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameIndexMetaList.Unmarshal(m, b)
}
func (m *FlameIndexMetaList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameIndexMetaList.Marshal(b, m, deterministic)
}
func (m *FlameIndexMetaList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameIndexMetaList.Merge(m, src)
}
func (m *FlameIndexMetaList) XXX_Size() int {
	return xxx_messageInfo_FlameIndexMetaList.Size(m)
}
func (m *FlameIndexMetaList) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameIndexMetaList.DiscardUnknown(m)
}

var xxx_messageInfo_FlameIndexMetaList proto.InternalMessageInfo

func (m *FlameIndexMetaList) GetFlameIndexMetaList() []*FlameIndexMeta {
	if m != nil {
		return m.FlameIndexMetaList
	}
	return nil
}

type FlameNamespaceList struct {
	FlameNamespaceList   [][]byte `protobuf:"bytes,1,rep,name=flameNamespaceList,proto3" json:"flameNamespaceList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlameNamespaceList) Reset()         { *m = FlameNamespaceList{} }
func (m *FlameNamespaceList) String() string { return proto.CompactTextString(m) }
func (*FlameNamespaceList) ProtoMessage()    {}
func (*FlameNamespaceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{8}
}

func (m *FlameNamespaceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameNamespaceList.Unmarshal(m, b)
}
func (m *FlameNamespaceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameNamespaceList.Marshal(b, m, deterministic)
}
func (m *FlameNamespaceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameNamespaceList.Merge(m, src)
}
func (m *FlameNamespaceList) XXX_Size() int {
	return xxx_messageInfo_FlameNamespaceList.Size(m)
}
func (m *FlameNamespaceList) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameNamespaceList.DiscardUnknown(m)
}

var xxx_messageInfo_FlameNamespaceList proto.InternalMessageInfo

func (m *FlameNamespaceList) GetFlameNamespaceList() [][]byte {
	if m != nil {
		return m.FlameNamespaceList
	}
	return nil
}

type FlameUser struct {
	FlameUserType        FlameUser_FlameUserType `protobuf:"varint,1,opt,name=flameUserType,proto3,enum=pb.FlameUser_FlameUserType" json:"flameUserType,omitempty"`
	Roles                string                  `protobuf:"bytes,2,opt,name=roles,proto3" json:"roles,omitempty"`
	Username             string                  `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string                  `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt            uint64                  `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            uint64                  `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	UserData             []byte                  `protobuf:"bytes,7,opt,name=userData,proto3" json:"userData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *FlameUser) Reset()         { *m = FlameUser{} }
func (m *FlameUser) String() string { return proto.CompactTextString(m) }
func (*FlameUser) ProtoMessage()    {}
func (*FlameUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{9}
}

func (m *FlameUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameUser.Unmarshal(m, b)
}
func (m *FlameUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameUser.Marshal(b, m, deterministic)
}
func (m *FlameUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameUser.Merge(m, src)
}
func (m *FlameUser) XXX_Size() int {
	return xxx_messageInfo_FlameUser.Size(m)
}
func (m *FlameUser) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameUser.DiscardUnknown(m)
}

var xxx_messageInfo_FlameUser proto.InternalMessageInfo

func (m *FlameUser) GetFlameUserType() FlameUser_FlameUserType {
	if m != nil {
		return m.FlameUserType
	}
	return FlameUser_SUPER_USER
}

func (m *FlameUser) GetRoles() string {
	if m != nil {
		return m.Roles
	}
	return ""
}

func (m *FlameUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FlameUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *FlameUser) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *FlameUser) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *FlameUser) GetUserData() []byte {
	if m != nil {
		return m.UserData
	}
	return nil
}

type FlameUserList struct {
	FlameUserList        []*FlameUser `protobuf:"bytes,1,rep,name=flameUserList,proto3" json:"flameUserList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FlameUserList) Reset()         { *m = FlameUserList{} }
func (m *FlameUserList) String() string { return proto.CompactTextString(m) }
func (*FlameUserList) ProtoMessage()    {}
func (*FlameUserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{10}
}

func (m *FlameUserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameUserList.Unmarshal(m, b)
}
func (m *FlameUserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameUserList.Marshal(b, m, deterministic)
}
func (m *FlameUserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameUserList.Merge(m, src)
}
func (m *FlameUserList) XXX_Size() int {
	return xxx_messageInfo_FlameUserList.Size(m)
}
func (m *FlameUserList) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameUserList.DiscardUnknown(m)
}

var xxx_messageInfo_FlameUserList proto.InternalMessageInfo

func (m *FlameUserList) GetFlameUserList() []*FlameUser {
	if m != nil {
		return m.FlameUserList
	}
	return nil
}

type FlameUsernameList struct {
	FlameUsernameList    []string `protobuf:"bytes,1,rep,name=flameUsernameList,proto3" json:"flameUsernameList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlameUsernameList) Reset()         { *m = FlameUsernameList{} }
func (m *FlameUsernameList) String() string { return proto.CompactTextString(m) }
func (*FlameUsernameList) ProtoMessage()    {}
func (*FlameUsernameList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{11}
}

func (m *FlameUsernameList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameUsernameList.Unmarshal(m, b)
}
func (m *FlameUsernameList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameUsernameList.Marshal(b, m, deterministic)
}
func (m *FlameUsernameList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameUsernameList.Merge(m, src)
}
func (m *FlameUsernameList) XXX_Size() int {
	return xxx_messageInfo_FlameUsernameList.Size(m)
}
func (m *FlameUsernameList) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameUsernameList.DiscardUnknown(m)
}

var xxx_messageInfo_FlameUsernameList proto.InternalMessageInfo

func (m *FlameUsernameList) GetFlameUsernameList() []string {
	if m != nil {
		return m.FlameUsernameList
	}
	return nil
}

type FlameAccessControl struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Namespace            []byte   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Permission           []byte   `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	CreatedAt            uint64   `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            uint64   `protobuf:"varint,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlameAccessControl) Reset()         { *m = FlameAccessControl{} }
func (m *FlameAccessControl) String() string { return proto.CompactTextString(m) }
func (*FlameAccessControl) ProtoMessage()    {}
func (*FlameAccessControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{12}
}

func (m *FlameAccessControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameAccessControl.Unmarshal(m, b)
}
func (m *FlameAccessControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameAccessControl.Marshal(b, m, deterministic)
}
func (m *FlameAccessControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameAccessControl.Merge(m, src)
}
func (m *FlameAccessControl) XXX_Size() int {
	return xxx_messageInfo_FlameAccessControl.Size(m)
}
func (m *FlameAccessControl) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameAccessControl.DiscardUnknown(m)
}

var xxx_messageInfo_FlameAccessControl proto.InternalMessageInfo

func (m *FlameAccessControl) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FlameAccessControl) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *FlameAccessControl) GetPermission() []byte {
	if m != nil {
		return m.Permission
	}
	return nil
}

func (m *FlameAccessControl) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *FlameAccessControl) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type FlameAccessControlList struct {
	FlameAccessControlList []*FlameAccessControl `protobuf:"bytes,1,rep,name=flameAccessControlList,proto3" json:"flameAccessControlList,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}              `json:"-"`
	XXX_unrecognized       []byte                `json:"-"`
	XXX_sizecache          int32                 `json:"-"`
}

func (m *FlameAccessControlList) Reset()         { *m = FlameAccessControlList{} }
func (m *FlameAccessControlList) String() string { return proto.CompactTextString(m) }
func (*FlameAccessControlList) ProtoMessage()    {}
func (*FlameAccessControlList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{13}
}

func (m *FlameAccessControlList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameAccessControlList.Unmarshal(m, b)
}
func (m *FlameAccessControlList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameAccessControlList.Marshal(b, m, deterministic)
}
func (m *FlameAccessControlList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameAccessControlList.Merge(m, src)
}
func (m *FlameAccessControlList) XXX_Size() int {
	return xxx_messageInfo_FlameAccessControlList.Size(m)
}
func (m *FlameAccessControlList) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameAccessControlList.DiscardUnknown(m)
}

var xxx_messageInfo_FlameAccessControlList proto.InternalMessageInfo

func (m *FlameAccessControlList) GetFlameAccessControlList() []*FlameAccessControl {
	if m != nil {
		return m.FlameAccessControlList
	}
	return nil
}

type FlameProposal struct {
	FlameProposalType    FlameProposal_FlameProposalType `protobuf:"varint,1,opt,name=flameProposalType,proto3,enum=pb.FlameProposal_FlameProposalType" json:"flameProposalType,omitempty"`
	FlameProposalData    []byte                          `protobuf:"bytes,2,opt,name=flameProposalData,proto3" json:"flameProposalData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *FlameProposal) Reset()         { *m = FlameProposal{} }
func (m *FlameProposal) String() string { return proto.CompactTextString(m) }
func (*FlameProposal) ProtoMessage()    {}
func (*FlameProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7378d1291c4337a, []int{14}
}

func (m *FlameProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlameProposal.Unmarshal(m, b)
}
func (m *FlameProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlameProposal.Marshal(b, m, deterministic)
}
func (m *FlameProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlameProposal.Merge(m, src)
}
func (m *FlameProposal) XXX_Size() int {
	return xxx_messageInfo_FlameProposal.Size(m)
}
func (m *FlameProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_FlameProposal.DiscardUnknown(m)
}

var xxx_messageInfo_FlameProposal proto.InternalMessageInfo

func (m *FlameProposal) GetFlameProposalType() FlameProposal_FlameProposalType {
	if m != nil {
		return m.FlameProposalType
	}
	return FlameProposal_BATCH_ACTION
}

func (m *FlameProposal) GetFlameProposalData() []byte {
	if m != nil {
		return m.FlameProposalData
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.FlameAction_FlameActionType", FlameAction_FlameActionType_name, FlameAction_FlameActionType_value)
	proto.RegisterEnum("pb.FlameIndexField_FlameIndexFieldType", FlameIndexField_FlameIndexFieldType_name, FlameIndexField_FlameIndexFieldType_value)
	proto.RegisterEnum("pb.FlameUser_FlameUserType", FlameUser_FlameUserType_name, FlameUser_FlameUserType_value)
	proto.RegisterEnum("pb.FlameProposal_FlameProposalType", FlameProposal_FlameProposalType_name, FlameProposal_FlameProposalType_value)
	proto.RegisterType((*FlameEntry)(nil), "pb.FlameEntry")
	proto.RegisterType((*FlameAction)(nil), "pb.FlameAction")
	proto.RegisterType((*FlameBatchAction)(nil), "pb.FlameBatchAction")
	proto.RegisterType((*FlameBatchRead)(nil), "pb.FlameBatchRead")
	proto.RegisterType((*FlameIndexField)(nil), "pb.FlameIndexField")
	proto.RegisterType((*FlameIndexDocument)(nil), "pb.FlameIndexDocument")
	proto.RegisterType((*FlameIndexMeta)(nil), "pb.FlameIndexMeta")
	proto.RegisterType((*FlameIndexMetaList)(nil), "pb.FlameIndexMetaList")
	proto.RegisterType((*FlameNamespaceList)(nil), "pb.FlameNamespaceList")
	proto.RegisterType((*FlameUser)(nil), "pb.FlameUser")
	proto.RegisterType((*FlameUserList)(nil), "pb.FlameUserList")
	proto.RegisterType((*FlameUsernameList)(nil), "pb.FlameUsernameList")
	proto.RegisterType((*FlameAccessControl)(nil), "pb.FlameAccessControl")
	proto.RegisterType((*FlameAccessControlList)(nil), "pb.FlameAccessControlList")
	proto.RegisterType((*FlameProposal)(nil), "pb.FlameProposal")
}

func init() { proto.RegisterFile("odsm.proto", fileDescriptor_e7378d1291c4337a) }

var fileDescriptor_e7378d1291c4337a = []byte{
	// 1011 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0xaf, 0xe3, 0x34, 0x89, 0x27, 0x7f, 0xea, 0x6e, 0x7b, 0x95, 0x81, 0x13, 0x54, 0xcb, 0x03,
	0x7d, 0x40, 0x11, 0xea, 0x49, 0x48, 0x3c, 0xba, 0x89, 0x8f, 0x8b, 0x94, 0x38, 0x61, 0xeb, 0x1c,
	0xe5, 0x29, 0x72, 0xed, 0x8d, 0x2e, 0xc2, 0xb1, 0x23, 0xdb, 0x39, 0x28, 0x9f, 0x00, 0xbe, 0x08,
	0x0f, 0x48, 0xf0, 0x1d, 0x78, 0xe6, 0x4b, 0xa1, 0x5d, 0xaf, 0xed, 0xb5, 0x93, 0xc2, 0xc3, 0xbd,
	0xed, 0xfc, 0x66, 0xe6, 0xe7, 0x9d, 0xdf, 0xcc, 0xc8, 0x0b, 0x10, 0xf9, 0xc9, 0x76, 0xb8, 0x8b,
	0xa3, 0x34, 0x42, 0x8d, 0xdd, 0x23, 0x26, 0x00, 0xaf, 0x03, 0x77, 0x4b, 0xad, 0x30, 0x8d, 0x9f,
	0xd0, 0x4b, 0xd0, 0x42, 0x77, 0x4b, 0x93, 0x9d, 0xeb, 0x51, 0x43, 0xb9, 0x56, 0x6e, 0x7a, 0xa4,
	0x04, 0x90, 0x0e, 0xea, 0x8f, 0xf4, 0xc9, 0x68, 0x70, 0x9c, 0x1d, 0xd1, 0x25, 0x9c, 0xbe, 0x77,
	0x83, 0x3d, 0x35, 0x54, 0x8e, 0x65, 0x06, 0xfe, 0x47, 0x81, 0x2e, 0x27, 0x35, 0xbd, 0x74, 0x13,
	0x85, 0x68, 0x02, 0x67, 0xeb, 0xd2, 0x74, 0x9e, 0x76, 0x19, 0xf7, 0xe0, 0xf6, 0xb3, 0xe1, 0xee,
	0x71, 0x28, 0x45, 0xca, 0x67, 0x16, 0x46, 0xea, 0x79, 0x68, 0x08, 0xb0, 0x2e, 0xae, 0xcb, 0x6f,
	0xd2, 0xbd, 0x1d, 0x14, 0x2c, 0x1c, 0x25, 0x52, 0x04, 0x36, 0xe1, 0xac, 0xc6, 0x89, 0x00, 0x5a,
	0x23, 0x62, 0x99, 0x8e, 0xa5, 0x9f, 0xb0, 0xf3, 0x72, 0x31, 0x66, 0x67, 0x85, 0x9d, 0xc7, 0xd6,
	0xd4, 0x72, 0x2c, 0xbd, 0xc1, 0xce, 0xe6, 0x62, 0x61, 0xd9, 0x63, 0x5d, 0xc5, 0x33, 0xd0, 0x39,
	0xc5, 0x9d, 0x9b, 0x7a, 0xef, 0x44, 0x45, 0xdf, 0x54, 0x2a, 0x9a, 0x6e, 0x92, 0xd4, 0x50, 0xae,
	0xd5, 0x9b, 0xee, 0xed, 0x59, 0xad, 0x22, 0x52, 0x8f, 0xc3, 0x6f, 0x60, 0x50, 0xd2, 0x11, 0xea,
	0xfa, 0xe8, 0x6b, 0x18, 0x94, 0x37, 0x96, 0xb8, 0xea, 0x75, 0xd5, 0xa2, 0xf0, 0x9f, 0xaa, 0x28,
	0x6e, 0x12, 0xfa, 0xf4, 0xe7, 0xd7, 0x1b, 0x1a, 0xf8, 0xe8, 0x07, 0xb8, 0x58, 0x57, 0x21, 0x49,
	0xee, 0x2f, 0x0a, 0xc2, 0xd2, 0x5d, 0xb7, 0xb9, 0xec, 0xc7, 0x38, 0x10, 0x82, 0x26, 0x1b, 0x05,
	0x2e, 0xba, 0x46, 0xf8, 0x19, 0x7d, 0x0c, 0x1d, 0x37, 0x74, 0x83, 0xa7, 0x5f, 0x68, 0xcc, 0x47,
	0x40, 0x23, 0x85, 0x8d, 0x0c, 0x68, 0xd3, 0xd0, 0x7d, 0x0c, 0xa8, 0x6f, 0x34, 0xaf, 0x95, 0x9b,
	0x0e, 0xc9, 0x4d, 0x36, 0x35, 0x1b, 0xc6, 0x6d, 0x9c, 0x72, 0x3c, 0x33, 0x18, 0x9a, 0xa4, 0x51,
	0x4c, 0x8d, 0x56, 0x86, 0x72, 0x03, 0x0d, 0x01, 0x6d, 0x42, 0x2f, 0xd8, 0xfb, 0xd4, 0xa1, 0xf1,
	0xf6, 0x2d, 0xf5, 0xd2, 0x28, 0x4e, 0x8c, 0x36, 0x0f, 0x39, 0xe2, 0x41, 0x18, 0x7a, 0x02, 0x9d,
	0x84, 0x66, 0x10, 0x18, 0x1d, 0x1e, 0x59, 0xc1, 0xd8, 0x94, 0xfb, 0x91, 0xf7, 0x96, 0xcd, 0x6a,
	0x62, 0x68, 0x3c, 0xa0, 0x04, 0xf0, 0xf7, 0x70, 0x71, 0x44, 0x13, 0xd4, 0x81, 0xa6, 0x63, 0x3d,
	0x38, 0xfa, 0x09, 0xea, 0x42, 0xdb, 0x5e, 0xce, 0x2c, 0x32, 0x19, 0xe9, 0x0a, 0x33, 0xee, 0xe6,
	0xf3, 0xa9, 0x65, 0xda, 0x7a, 0x03, 0xf5, 0x41, 0xfb, 0xd6, 0x9a, 0xaf, 0x16, 0xf3, 0x89, 0xed,
	0xe8, 0x2a, 0x33, 0xd9, 0x6c, 0xad, 0x9c, 0xc9, 0xcc, 0xd2, 0x9b, 0xf8, 0x37, 0x05, 0x50, 0xc9,
	0x3c, 0x8e, 0xbc, 0xfd, 0x96, 0x86, 0x69, 0xa1, 0xab, 0x22, 0xe9, 0x6a, 0x40, 0xdb, 0xa7, 0x6b,
	0x77, 0x1f, 0xa4, 0x5c, 0xee, 0x0e, 0xc9, 0x4d, 0x64, 0x1d, 0x34, 0x98, 0x4f, 0x8c, 0xca, 0x27,
	0xe6, 0xe2, 0x48, 0x83, 0xc9, 0xb1, 0x78, 0xfc, 0x6b, 0x43, 0x8c, 0x21, 0xc7, 0x67, 0x34, 0x75,
	0xff, 0x67, 0xf7, 0x0d, 0x68, 0xbf, 0xa7, 0x71, 0xb2, 0x89, 0x42, 0x7e, 0xa3, 0x3e, 0xc9, 0x4d,
	0xb9, 0xcf, 0x6a, 0xb5, 0xcf, 0x52, 0x15, 0xcd, 0x6a, 0x15, 0x2f, 0x41, 0xf3, 0x62, 0xea, 0xa6,
	0xd4, 0x37, 0x53, 0x3e, 0x05, 0x4d, 0x52, 0x02, 0xcc, 0xbb, 0xdf, 0xf9, 0xc2, 0xdb, 0xca, 0xbc,
	0x05, 0x80, 0x6c, 0xb8, 0x5a, 0x1f, 0xa8, 0xc8, 0x45, 0x68, 0x73, 0x11, 0xae, 0xaa, 0x22, 0xe4,
	0x11, 0xe4, 0x99, 0x2c, 0xfc, 0x20, 0x77, 0x85, 0x29, 0xc1, 0x50, 0x74, 0x07, 0x68, 0x7d, 0x80,
	0x8a, 0xc5, 0x44, 0xd5, 0x2f, 0x30, 0x2f, 0x39, 0x12, 0x8d, 0xc7, 0x82, 0xd9, 0xce, 0x55, 0xe4,
	0xcc, 0x43, 0xc1, 0x5c, 0x41, 0x39, 0x73, 0x8f, 0x1c, 0xf1, 0xe0, 0xdf, 0x1b, 0xa0, 0x71, 0x9a,
	0x65, 0x42, 0x63, 0x64, 0x42, 0x7f, 0x9d, 0x1b, 0xd2, 0x6a, 0x7f, 0x52, 0x5c, 0x89, 0x39, 0xca,
	0x13, 0x5f, 0xe7, 0x6a, 0x06, 0x5b, 0xb4, 0x38, 0x0a, 0x68, 0x22, 0x36, 0x39, 0x33, 0xd8, 0x2a,
	0xef, 0x13, 0x1a, 0xf3, 0x51, 0x14, 0xab, 0x9c, 0xdb, 0xcc, 0xb7, 0x73, 0x93, 0xe4, 0xa7, 0x28,
	0xce, 0x76, 0x59, 0x23, 0x85, 0xfd, 0x41, 0xad, 0x14, 0xdf, 0x1c, 0xbb, 0xa9, 0xcb, 0x57, 0xba,
	0x47, 0x0a, 0x1b, 0x7f, 0x05, 0xfd, 0x4a, 0x15, 0x68, 0x00, 0x70, 0xbf, 0x5c, 0x58, 0x64, 0xb5,
	0xbc, 0xb7, 0x88, 0x7e, 0x82, 0xce, 0xa0, 0x6b, 0xcf, 0xc9, 0xcc, 0x9c, 0x66, 0x80, 0x82, 0xc7,
	0x52, 0x06, 0x57, 0xfa, 0x95, 0xa4, 0x95, 0xd4, 0xbe, 0x7e, 0x45, 0x2b, 0x52, 0x8d, 0xc1, 0x26,
	0x9c, 0x17, 0x3e, 0x56, 0x3c, 0x67, 0xfa, 0x12, 0xce, 0xd7, 0x75, 0x90, 0xb3, 0x69, 0xe4, 0xd0,
	0x81, 0xff, 0xc8, 0x17, 0xdd, 0xf4, 0x3c, 0x9a, 0x24, 0xa3, 0x28, 0x4c, 0xe3, 0x28, 0xa8, 0x28,
	0xac, 0xd4, 0x14, 0xae, 0x2c, 0x5f, 0xa3, 0xbe, 0x7c, 0x9f, 0x02, 0xec, 0x68, 0xbc, 0xdd, 0x24,
	0x7c, 0xff, 0xb2, 0x7f, 0xad, 0x84, 0x54, 0x7b, 0xd0, 0xfc, 0xcf, 0x1e, 0x9c, 0xd6, 0x7a, 0x80,
	0xdf, 0xc1, 0xd5, 0xe1, 0x5d, 0x79, 0xd1, 0xf9, 0xa2, 0x1d, 0x78, 0x84, 0x8e, 0x57, 0xd2, 0xbf,
	0x4e, 0x8a, 0x20, 0xcf, 0x64, 0xe1, 0xbf, 0x55, 0xd1, 0xa0, 0x45, 0x1c, 0xed, 0xa2, 0xc4, 0x0d,
	0xd0, 0x77, 0x42, 0xd6, 0x1c, 0x90, 0x06, 0xfa, 0xf3, 0x82, 0x3c, 0x77, 0x56, 0x2d, 0x3e, 0xd8,
	0x87, 0xd9, 0x45, 0xa7, 0x72, 0x90, 0xcf, 0x56, 0x26, 0xe8, 0xa1, 0x03, 0xff, 0xd5, 0x10, 0xdd,
	0xae, 0x70, 0xe8, 0xd0, 0xbb, 0x33, 0x9d, 0xd1, 0x9b, 0x95, 0x39, 0x72, 0x26, 0x73, 0x3b, 0x9b,
	0xb5, 0xec, 0xcd, 0x20, 0x66, 0x8d, 0x01, 0xd9, 0xc3, 0x21, 0x03, 0x1a, 0x0c, 0xc8, 0x5e, 0x0f,
	0x19, 0xa0, 0xa2, 0x17, 0x70, 0x2e, 0x52, 0x26, 0xf6, 0xd8, 0x7a, 0x58, 0xcd, 0x2c, 0xc7, 0xd4,
	0x9b, 0x0c, 0x16, 0x89, 0x12, 0x7c, 0xca, 0x60, 0x91, 0x2e, 0xc1, 0x2d, 0xf4, 0x11, 0xbc, 0x10,
	0x24, 0xe6, 0x68, 0x64, 0xdd, 0xdf, 0xaf, 0x46, 0x73, 0xdb, 0x21, 0xf3, 0xa9, 0xde, 0x66, 0x2e,
	0x41, 0x54, 0x73, 0x75, 0x98, 0x4b, 0x90, 0xd5, 0x5c, 0x1a, 0x5b, 0xa2, 0xac, 0x34, 0x7e, 0x4b,
	0x40, 0x97, 0xa0, 0x67, 0xb6, 0xf4, 0xd9, 0x2e, 0x32, 0xe0, 0x32, 0x17, 0xa0, 0x92, 0xdf, 0x7b,
	0x6c, 0xf1, 0x97, 0xe3, 0xab, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x57, 0xdc, 0x34, 0x47,
	0x0a, 0x00, 0x00,
}
